//>>built
require({cache:{"widgets/AttributeTable/utils":function(){define("dojo/_base/lang dojo/_base/array jimu/LayerInfos/LayerInfos dojo/Deferred dojo/promise/all exports dojo/store/Observable dojo/store/Cache dojo/store/Memory esri/lang ./FeatureLayerQueryStore jimu/utils".split(" "),function(h,m,s,p,c,d,f,u,g,l,t,q){function r(b){var a=[],k=[];m.forEach(b,function(e){var n=a.indexOf(e.name);0>n?a.push(e.name):(k.push(b[n]),k.push(e))});m.forEach(k,function(a){a.name=a.name+"-"+a.id})}d.readLayerInfosObj=
function(b){return s.getInstance(b,b.itemInfo)};d.readLayerInfosFromMap=function(b){var a=new p;s.getInstance(b,b.itemInfo).then(h.hitch(this,function(b){var e=[];b.traversal(h.hitch(this,function(a){e.push(a)}));b=b.getTableInfoArray();e=e.concat(b);a.resolve(e)}),h.hitch(this,function(b){console.error(b);a.reject(b)}));return a.promise};d.createCSVStr=function(b,a,k,e){var n=new p,c="",f=0,g=0,h="",l="";try{m.forEach(a,function(a){c=c+h+(a.alias||a.name);h=","});for(var c=c+"\r\n",f=b.length,g=
a.length,u=0;u<f;u++){for(var h="",q=0;q<g;q++){var x=a[q],l=d.getExportValue(b[u][x.name],x,k,b[u][k],e);!l&&"number"!==typeof l&&(l="");l&&/[",\r\n]/g.test(l)&&(l='"'+l.replace(/(")/g,'""')+'"');c=c+h+l;h=","}c+="\r\n"}n.resolve(c)}catch(t){console.error(t),n.resolve("")}return n};d.getExportValue=function(b,a,k,e,n){var c=!!a.domain,f="esriFieldTypeDate"===a.type,l=k&&a.name===k;return f?d.dateFormatter(b):c?d.getCodeValue(a.domain,b):!c&&!f&&!l?(c=null,k&&n&&0<n.length&&(k=m.filter(n,function(a){return a.name===
e}))&&(k.domains&&k.domains[a.name]&&k.domains[a.name].codedValues)&&(c=d.getCodeValue(k.domains[a.name],b)),null!==c?c:b):b};d.generateColumnsFromFields=function(b,a,k,e){var n={};m.forEach(b,h.hitch(d,function(c,f){var g="field"+f,u=!!c.domain,q="esriFieldTypeDate"===c.type,p=a&&c.name===a;n[g]={label:c.alias||c.name,className:g,hidden:!c.show&&l.isDefined(c.show),unhidable:!c.show&&l.isDefined(c.show)&&c._pk,field:c.name};n[g].sortable=!!e;if("esriFieldTypeString"===b[f].type)n[g].formatter=h.hitch(d,
d.urlFormatter);else if("esriFieldTypeDate"===b[f].type)n[g].formatter=h.hitch(d,d.dateFormatter);else if("esriFieldTypeDouble"===b[f].type||"esriFieldTypeSingle"===b[f].type||"esriFieldTypeInteger"===b[f].type||"esriFieldTypeSmallInteger"===b[f].type)n[g].formatter=h.hitch(d,d.numberFormatter);u?n[g].get=h.hitch(d,function(a,b){return this.getCodeValue(a.domain,b[a.name])},c):p?n[g].get=h.hitch(d,function(a,b,e){return this.getTypeName(e[a.name],b)},c,k):!u&&(!q&&!p)&&(n[g].get=h.hitch(d,function(a,
b,e,k){var c=null;b&&e&&0<e.length&&(e=(e=m.filter(e,h.hitch(d,function(a){return a.name===k[b]})))&&e[0]||null)&&(e.domains&&e.domains[a.name]&&e.domains[a.name].codedValues)&&(c=this.getCodeValue(e.domains[a.name],k[a.name]));return(a=null!==c?c:k[a.name])||isFinite(a)?a:""},c,a,k))}));return n};d.getTypeName=function(b,a){for(var k=a.length,e=0;e<k;e++)if(b===a[e].id)return a[e].name;return b};d.getCodeValue=function(b,a){if(b.codedValues){for(var k=0,e=b.codedValues.length;k<e;k++){var c=b.codedValues[k];
if(a===c.code)return c.name}return a}return a||null};d.urlFormatter=function(b){if(b&&"string"===typeof b){var a=b.indexOf("http:");-1===a&&(a=b.indexOf("https:"));if(-1<a&&-1===b.indexOf("href\x3d")){var k=b.indexOf(" ",a);-1===k&&(k=b.length);var e=b.substring(a,k);b=b.substring(0,a)+'\x3cA href\x3d"'+e+'" target\x3d"_blank"\x3e'+e+"\x3c/A\x3e"+b.substring(k,b.length)}}return b||""};d.dateFormatter=function(b){b&&(b=q.localizeDate(new Date(b),{fullYear:!0}));return b||""};d.numberFormatter=function(b){if("number"===
typeof b){var a=(b.toString().split(".")[1]||"").length;b=q.localizeNumber(b,{places:a});return'\x3cspan class\x3d"jimu-numeric-value"\x3e'+(b||"")+"\x3c/span\x3e"}return b};d.readLayerObjectsFromMap=function(b){var a=new p,k=[];this.readLayerInfosFromMap(b).then(h.hitch(this,function(b){m.forEach(b,h.hitch(this,function(a){k.push(a.getLayerObject())}));c(k).then(h.hitch(this,function(b){a.resolve(b)}),h.hitch(this,function(b){a.reject(b);console.error(b)}))}),h.hitch(this,function(b){a.reject(b)}));
return a.promise};d.readSupportTableInfoFromLayerInfos=function(b){var a=new p,k=[];m.forEach(b,h.hitch(this,function(a){k.push(a.getSupportTableInfo())}));c(k).then(h.hitch(this,function(e){e=h.clone(e);m.forEach(e,function(a,e){a.id=b[e].id});a.resolve(e)}),function(b){a.reject(b)});return a.promise};d.readConfigLayerInfosFromMap=function(b){var a=new p,k=[];this.readLayerInfosFromMap(b).then(h.hitch(this,function(b){var n=[];m.forEach(b,function(a){k.push(a.getSupportTableInfo())});c(k).then(h.hitch(this,
function(k){m.forEach(k,h.hitch(this,function(a,k){a.isSupportedLayer&&(b[k].name=b[k].title,n.push(b[k]))}));r(n);a.resolve(n)}),h.hitch(this,function(b){a.reject(b)}))}),h.hitch(this,function(b){a.reject(b)}));return a.promise};d.getConfigInfosFromLayerInfos=function(b){return m.map(b,function(a){return d.getConfigInfoFromLayerInfo(a)})};d.getConfigInfoFromLayerInfo=function(b){var a={};a.name=b.name||b.title;a.id=b.id;a.show=b.isShowInMap();a.layer={url:b.getUrl()};if((b=b.getPopupInfo())&&!b.description)a.layer.fields=
m.map(b.fieldInfos,function(a){return{name:a.fieldName,alias:a.label,show:a.visible}});return a};d.generateCacheStore=function(b,a,k,e,c){b=new t({layer:b,objectIds:b._objectIds||null,totalCount:a,batchCount:k,where:e||"1\x3d1",spatialFilter:c});a=new g;return new u(b,a,{})};d.generateMemoryStore=function(b,a){return new f(new g({data:b||[],idProperty:a}))}})},"dojo/store/Observable":function(){define(["../_base/kernel","../_base/lang","../when","../_base/array"],function(h,m,s,p){h=function(c){function d(f,
d){var g=c[f];g&&(c[f]=function(b){var a;"put"===f&&(a=c.getIdentity(b));if(l)return g.apply(this,arguments);l=!0;try{var k=g.apply(this,arguments);s(k,function(e){d("object"==typeof e&&e||b,a)});return k}finally{l=!1}})}var f=[],h=0;c=m.delegate(c);c.notify=function(c,d){h++;for(var g=f.slice(),b=0,a=g.length;b<a;b++)g[b](c,d)};var g=c.query;c.query=function(d,l){l=l||{};var r=g.apply(this,arguments);if(r&&r.forEach){var b=m.mixin({},l);delete b.start;delete b.count;var a=c.queryEngine&&c.queryEngine(d,
b),k=h,e=[],n;r.observe=function(b,d){1==e.push(b)&&f.push(n=function(b,n){s(r,function(f){var g=f.length!=l.count,m,v;if(++k!=h)throw Error("Query is out of date, you must observe() the query prior to any data modifications");var s,t=-1,r=-1;if(void 0!==n){m=0;for(v=f.length;m<v;m++){var w=f[m];if(c.getIdentity(w)==n){s=w;t=m;(a||!b)&&f.splice(m,1);break}}}if(a){if(b&&(a.matches?a.matches(b):a([b]).length))m=-1<t?t:f.length,f.splice(m,0,b),r=p.indexOf(a(f),b),f.splice(m,1),l.start&&0==r||!g&&r==
f.length?r=-1:f.splice(r,0,b)}else b&&(void 0!==n?r=t:l.start||(r=c.defaultIndex||0,f.splice(r,0,b)));if((-1<t||-1<r)&&(d||!a||t!=r)){g=e.slice();for(m=0;f=g[m];m++)f(b||s,t,r)}})});var g={};g.remove=g.cancel=function(){var a=p.indexOf(e,b);-1<a&&(e.splice(a,1),e.length||f.splice(p.indexOf(f,n),1))};return g}}return r};var l;d("put",function(f,g){c.notify(f,g)});d("add",function(f){c.notify(f)});d("remove",function(f){c.notify(void 0,f)});return c};m.setObject("dojo.store.Observable",h);return h})},
"dojo/store/Cache":function(){define(["../_base/lang","../when"],function(h,m){var s=function(p,c,d){d=d||{};return h.delegate(p,{query:function(f,h){var g=p.query(f,h);g.forEach(function(f){(!d.isLoaded||d.isLoaded(f))&&c.put(f)});return g},queryEngine:p.queryEngine||c.queryEngine,get:function(f,d){return m(c.get(f),function(g){return g||m(p.get(f,d),function(g){g&&c.put(g,{id:f});return g})})},add:function(f,d){return m(p.add(f,d),function(g){c.add(g&&"object"==typeof g?g:f,d);return g})},put:function(f,
d){c.remove(d&&d.id||this.getIdentity(f));return m(p.put(f,d),function(g){c.put(g&&"object"==typeof g?g:f,d);return g})},remove:function(f,d){return m(p.remove(f,d),function(g){return c.remove(f,d)})},evict:function(f){return c.remove(f)}})};h.setObject("dojo.store.Cache",s);return s})},"widgets/AttributeTable/FeatureLayerQueryStore":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/array esri/tasks/query esri/tasks/QueryTask ./FeatureLayerQueryResult".split(" "),function(h,m,s,p,c,
d){return h(null,{queryUrl:"",idProperty:"id",data:null,_entityData:null,constructor:function(f){h.safeMixin(this,f);this.data=[];this._entityData=[];this.layer=f.layer;this.objectIds=f.objectIds;this.where=f.where;this.orderByFields=f.orderByFields;this.totalCount=f.totalCount;this.batchCount=f.batchCount||25;this.idProperty=this.layer.objectIdField;this.spatialFilter=f.spatialFilter;this.layer&&this.layer.url&&(this.queryTask=new c(this.layer.url))},get:function(c){return this.data[c]},getIdentity:function(c){return c[this.idProperty]},
query:function(c,h){var g=new p,l=h&&h.start||0,t=this.batchCount,q=null;"function"===typeof c?q=c(this._entityData):"[object Array]"===Object.prototype.toString.call(c)&&(q=c);if(this.objectIds)q=q?q:this.objectIds,g.objectIds=q.length>=l+this.batchCount?q.slice(l,l+t):q.slice(l);else if(q&&0<q.length?g.objectIds=q.length>=l+this.batchCount?q.slice(l,l+t):q.slice(l):(g.start=l,g.num=t,g.where=this.where,g.geometry=this.spatialFilter,g.spatialRelationship=p.SPATIAL_REL_INTERSECTS),(l=h.sort)&&0<l.length)l=
s.map(l,function(b){return b.attribute+" "+(b.descending?"DESC":"ASC")}),g.orderByFields=l;g.returnGeometry=!1;g.outFields=["*"];var r=this.totalCount,l=null,l=!g.where;if(!(g.objectIds&&0<g.objectIds.length)&&l)return new d([]);l=this.queryTask?this.queryTask.execute(g):this.layer.queryFeatures(g);l.total=l.then(m.hitch(this,function(b){var a=0,k=this.layer.objectIdField;if(this.objectIds){if(!k)for(a=0;a<b.fields.length;a++)if("esriFieldTypeOID"===b.fields[a].type){k=b.fields[a].name;break}for(var e=
{},a=0;a<b.features.length;a++)e[b.features[a].attributes[k]]=b.features[a];b.features=s.map(g.objectIds,function(a){return e[a]})}for(a=0;a<b.features.length;a++)b.features[a]&&(b.features[a]=b.features[a].attributes,this.data[b.features[a][k]]=b.features[a],this._entityData.push(b.features[a]));b=b.features;return r}),function(){console.log("FeatureLayerQueryStore queryFeatures failed.");return 0});return new d(l)}})})},"widgets/AttributeTable/FeatureLayerQueryResult":function(){define("esri/main dojo/_base/lang dojo/_base/kernel dojo/_base/Deferred dojo/DeferredList dojo/_base/array".split(" "),
function(h,m,s,p){var c=function(d){function f(f){d[f]||(d[f]=function(){var g=arguments;return p.when(d,function(d){Array.prototype.unshift.call(g,d.features||d);return c(s[f].apply(s,g))})})}if(!d)return d;d.then&&(d=m.delegate(d));d.total||(d.total=p.when(d,function(c){return h._isDefined(c.total)?c.total:c.length||0}));f("forEach");f("filter");f("map");f("some");f("every");return d};return c})},"widgets/AttributeTable/setting/_build-generate_module":function(){define(["dojo/text!./Setting.html",
"dojo/text!./css/style.css","dojo/i18n!./nls/strings"],function(){})},"url:widgets/AttributeTable/setting/Setting.html":'\x3cdiv style\x3d"width:100%;"\x3e\r\n  \x3cdiv data-dojo-attach-point\x3d"tableLayerInfos" class\x3d"table-layer-infos"\x3e\x3c/div\x3e\r\n  \x3c!-- \x3cdiv data-dojo-attach-point\x3d"tableEditInfosError" style\x3d"display:none"\x3e\x3c/div\x3e --\x3e\r\n  \x3cdiv class\x3d"table-options jimu-ellipsis"\x3e\r\n\t\t\x3cdiv data-dojo-attach-point\x3d"exportcsv" checked \r\n        data-dojo-type\x3d"jimu/dijit/CheckBox" label\x3d"${nls.exportCSV}"\x3e\x3c/div\x3e\r\n  \t\x3cdiv data-dojo-attach-point\x3d"expand" data-dojo-type\x3d"jimu/dijit/CheckBox" label\x3d"${nls.expand}"\x3e\x3c/div\x3e\r\n  \x3c/div\x3e\r\n\x3c/div\x3e\r\n',
"url:widgets/AttributeTable/setting/css/style.css":".jimu-widget-attributetable-setting{margin:0; padding:0; font-size:14px; width: 100%; height: 100%; position: relative;}.jimu-widget-attributetable-setting .show{width: 120px;}.jimu-widget-attributetable-setting .symbol{width: 200px;}.jimu-widget-attributetable-setting .table-layer-infos{width: 100%; height: 550px;}.jimu-widget-attributetable-setting .table-options{margin-top: 10px;}.jimu-widget-attributetable-setting .jimu-checkbox{margin-right: 20px;}.jimu-widget-attributetable-setting .disable-checkbox{color: #e5e5e5;}",
"*now":function(h){h(['dojo/i18n!*preload*widgets/AttributeTable/setting/nls/Setting*["ar","cs","da","de","en","el","es","et","fi","fr","he","it","ja","ko","lt","lv","nb","nl","pl","pt-br","pt-pt","ro","ru","sv","th","tr","zh-cn","vi","zh-hk","zh-tw","ROOT"]'])}}});
define("dojo/_base/declare dijit/_WidgetsInTemplateMixin jimu/BaseWidgetSetting jimu/dijit/SimpleTable dojo/_base/lang dojo/_base/html dojo/_base/array dojo/on dojo/Deferred dojo/query jimu/dijit/Popup jimu/dijit/Message jimu/dijit/LoadingShelter ../utils".split(" "),function(h,m,s,p,c,d,f,u,g,l,t,q,r,b){return h([s,m],{baseClass:"jimu-widget-attributetable-setting",currentFieldTable:null,_allLayerFields:null,_layerInfos:null,_tableInfos:null,_delayedLayerInfos:null,_delayedLayerInfosAfterInit:null,
_unSpportQueryCampsite:null,startup:function(){this.inherited(arguments);this.config.layerInfos||(this.config.layerInfos=[]);this._allLayerFields=[];this._layerInfos=[];this._tableInfos=[];this._delayedLayerInfos=[];this._delayedLayerInfosAfterInit=[];this._unSpportQueryCampsite={};this.displayFieldsTable=new p({fields:[{name:"show",title:this.nls.show,width:"auto",type:"checkbox","class":"show"},{name:"label",title:this.nls.label,width:"60%",type:"text"},{name:"url",title:"url",type:"text",hidden:!0},
{name:"index",title:"index",type:"text",hidden:!0},{name:"actions",title:this.nls.actions,type:"actions",width:"20%",actions:["edit"],"class":"symbol"}],selectable:!0,autoHeight:!1});this.displayFieldsTable.placeAt(this.tableLayerInfos);d.setStyle(this.displayFieldsTable.domNode,{height:"100%"});this.displayFieldsTable.startup();this.shelter=new r({hidden:!0});this.shelter.placeAt(this.domNode.parentNode.parentNode||this.domNode);this.shelter.startup();this.shelter.show();b.readLayerInfosObj(this.map).then(c.hitch(this,
function(a){this.own(a.on("layerInfosChanged",c.hitch(this,this.onLayerInfosChanged)));this.own(u(this.displayFieldsTable,"actions-edit",c.hitch(this,this.editFieldsClick)));this.own(u(this.displayFieldsTable,"row-click",c.hitch(this,this._verifiedOnShowClick)));this.setConfig(this.config)}))},editFieldsClick:function(a){var b=l(".action-item-parent",a);if(b&&b.length)if(b=this.displayFieldsTable.getRowData(a),b.show){var e=parseInt(b.index,10);this.shelter.show();this._getLayerFields(e).then(c.hitch(this,
function(b){this.openFieldsDialog(a,b,e)}),c.hitch(this,function(a){console.error(a)})).always(c.hitch(this,function(){this.shelter.hide()}))}else var f=new q({message:this.nls.warning,buttons:[{label:this.nls.ok,onClick:c.hitch(this,function(){f.close()})}]})},_verifiedOnShowClick:function(a){var b=this.displayFieldsTable.getRowData(a),e=parseInt(b.index,10),c=null,c=this.config&&this.config.layerInfos&&0<this.config.layerInfos.length?this.config.layerInfos[e]:this._layerInfos[e],e=-1<this._unSpportQueryCampsite.layerNames.indexOf(c.name||
c.title);b.show&&e&&(new q({message:this.nls.unsupportQueryWarning}),b.show=!1,this.displayFieldsTable.editRow(a,b))},_getLayerFields:function(a){var b=new g,e=this._allLayerFields[a];e?b.resolve(e):this._layerInfos[a].getLayerObject().then(c.hitch(this,function(a){a.fields?b.resolve(a.fields):b.reject()}),c.hitch(this,function(a){b.reject(a)}));return b},openFieldsDialog:function(a,b,e){var d=this._createFieldsTable(b,e);this.currentFieldTable=d;this.own(u(d,"row-click",c.hitch(this,function(a){var b=
d.getData();if(!f.some(b,c.hitch(this,function(a){return a.show}))&&(new q({message:this.nls.fieldCheckWarning}),b=d.getRowData(a)))b.show=!0,d.editRow(a,b)})));var g=new t({titleLabel:this.nls.configureLayerFields,width:640,maxHeight:600,autoHeight:!0,content:d,buttons:[{label:this.nls.ok,onClick:c.hitch(this,function(){this._allLayerFields[e]=d.getData();g.close();g=null})},{label:this.nls.cancel,onClick:c.hitch(this,function(){g.close();g=null})}],onClose:function(){g=null}})},_createFieldsTable:function(a){for(var b=
new p({fields:[{name:"show",title:this.nls.fieldVisibility,type:"checkbox","class":"show"},{name:"name",title:this.nls.fieldName,type:"text"},{name:"alias",title:this.nls.fieldAlias,editable:!0,type:"text"},{name:"actions",title:this.nls.fieldActions,type:"actions",actions:["up","down"],"class":"symbol"}],selectable:!0,autoHeight:!1,style:{height:"300px",maxHeight:"300px"}}),e=0;e<a.length;e++)a[e].show=void 0===a[e].show?!0:!!a[e].show,b.addRow(a[e]);return b},setConfig:function(a){this.config=a;
this.displayFieldsTable.clear();this._allLayerFields=[];this._processTableData().then(c.hitch(this,function(a){this._init(a);this.shelter.hide()}),c.hitch(this,function(a){new q({message:a.message||a})}))},onLayerInfosChanged:function(a,b,e){"added"!==b||(!e||!a)||e.getSupportTableInfo().then(c.hitch(this,function(a){a.isSupportedLayer&&(this._layerInfos&&0===this._layerInfos.length?this._delayedLayerInfos.push(e):this._layerInfos&&(0<this._layerInfos.length&&!this._getLayerInfoById(e.id))&&(this._delayedLayerInfosAfterInit.push(e),
this._processDelayedLayerInfosAfterInit(this._delayedLayerInfosAfterInit)))}))},_processDelayedLayerInfosAfterInit:function(a){for(var c=this._layerInfos.length,e=0;e<a.length;e++){var d=b.getConfigInfoFromLayerInfo(a[e]);this.displayFieldsTable.addRow({label:d.name||d.title,url:d.layer.url,index:""+(c+e),show:d.show});this._allLayerFields.push(d.layer.fields);this._layerInfos.push(a[e])}},_processDelayedLayerInfos:function(){0<this._delayedLayerInfos.length&&(f.forEach(this._delayedLayerInfos,c.hitch(this,
function(a){this._getLayerInfoById(a.id)||this._layerInfos.push(a)})),this._delayedLayerInfos=[])},_processTableData:function(){var a=new g;b.readConfigLayerInfosFromMap(this.map).then(c.hitch(this,function(d){this._layerInfos=d;this._processDelayedLayerInfos();b.readSupportTableInfoFromLayerInfos(this._layerInfos).then(c.hitch(this,function(e){this._tableInfos=e;this.config&&this.config.layerInfos&&0<this.config.layerInfos.length?(e=f.filter(this.config.layerInfos,c.hitch(this,function(a){return this._getLayerInfoById(a.id)})),
this.config.layerInfos=e,this._unSpportQueryCampsite.fromConfig=!0,this._unSpportQueryCampsite.layerNames=this._getUnsupportQueryLayerNames(this.config.layerInfos),a.resolve(e)):(this._unSpportQueryCampsite.fromConfig=!1,this._unSpportQueryCampsite.layerNames=this._getUnsupportQueryLayerNames(this._layerInfos),a.resolve(b.getConfigInfosFromLayerInfos(d)))}),function(b){console.error(b);a.reject(b)})}),c.hitch(this,function(b){console.error(b);a.reject(b)}));return a},_getUnsupportQueryLayerNames:function(a){var b=
[];f.forEach(a,c.hitch(this,function(a){var c=this._getSupportTableInfoById(a.id);c&&!c.isSupportQuery&&b.push(a.name||a.title)}));return b},_init:function(a){for(var b=[],c=0;c<a.length;c++){var f=a[c].show&&this._getSupportTableInfoById(a[c].id).isSupportQuery;this.displayFieldsTable.addRow({label:a[c].name||a[c].title,url:a[c].layer.url,index:""+c,show:f});this._allLayerFields.push(a[c].layer.fields);this._unSpportQueryCampsite.fromConfig&&(f=(f=this._unSpportQueryCampsite.layerNames)&&-1<f.indexOf(a[c].name||
a[c].title),a[c].show&&f&&b.push(a[c].name||a[c].title))}this._unSpportQueryCampsite.fromConfig&&0<b.length&&new q({message:this.nls.unsupportQueryLayers+"\x3cbr\x3e\x3cbr\x3e"+b.toString()});this.config.hideExportButton?this.exportcsv.uncheck():this.exportcsv.check();this.config.initiallyExpand?this.expand.check():this.expand.uncheck();this._canUseOpenAtStart()&&(this.openAtStart?this.expand.check():this.expand.uncheck(),this.expand.status=!1,d.addClass(this.expand.domNode,"disable-checkbox"))},
_canUseOpenAtStart:function(){return this.closeable||!this.isOnScreen},_getLayerInfoById:function(a){for(var b=0,c=this._layerInfos.length;b<c;b++)if(this._layerInfos[b].id===a)return this._layerInfos[b]},_getSupportTableInfoById:function(a){for(var b=0,c=this._tableInfos.length;b<c;b++)if(this._tableInfos[b].id===a)return this._tableInfos[b]},getConfig:function(){var a=this.displayFieldsTable.getData(),b=[],d=a.length;if(this.config&&this.config.layerInfos&&0<this.config.layerInfos.length)f.forEach(a,
c.hitch(this,function(c,d){var f=this.config.layerInfos[d],e={};e.name=f.name||f.title;e.id=f.id;e.layer={};e.layer.url=a[d].url;e.layer.fields=this._allLayerFields[d];e.show=a[d].show;b.push(e)}));else for(var g=0;g<d;g++){var h={};h.name=this._layerInfos[g].name||this._layerInfos[g].title;h.id=this._layerInfos[g].id;h.layer={};h.layer.url=a[g].url;h.layer.fields=this._allLayerFields[g];h.show=a[g].show;b.push(h)}this.config.layerInfos=b;this.config.hideExportButton=!this.exportcsv.getValue();this._canUseOpenAtStart()||
(this.config.initiallyExpand=this.expand.getValue());return this.config}})});