//>>built
define(["./BaseVersionManager","./utils"],function(g,h){function f(){this.versions=[{version:"1.0",description:"The version embedded in portal 10.3 final.",upgrader:function(b){return b},compatible:!0},{version:"1.1",description:"The version embedded in online3.6, and used in developer edition 1.0.",upgrader:function(b){b.widgetOnScreen&&(b.widgetOnScreen.panel&&"themes/FoldableTheme/panels/TitlePanel/Panel"===b.widgetOnScreen.panel.uri)&&(b.widgetOnScreen.panel.uri="jimu/PreloadWidgetIconPanel");
return b},compatible:!0},{version:"1.2",description:"The version embedded in online3.7.",upgrader:function(b){var c=0;if(b.widgetOnScreen&&b.widgetOnScreen.widgets){for(var a=!1,c=0;c<b.widgetOnScreen.widgets.length;c++)"widgets/Splash/Widget"===b.widgetOnScreen.widgets[c].uri&&(a=!0);a||b.widgetOnScreen.widgets.push({uri:"widgets/Splash/Widget",visible:!1,positionRelativeTo:"browser",version:"1.2"});a=!1;for(c=0;c<b.widgetOnScreen.widgets.length;c++)"widgets/TimeSlider/Widget"===b.widgetOnScreen.widgets[c].uri&&
(a=!0);a||b.widgetOnScreen.widgets.push({uri:"widgets/TimeSlider/Widget",visible:!1,position:{bottom:55,left:7},version:"1.2"});a=!1;for(c=0;c<b.widgetOnScreen.widgets.length;c++)"widgets/Swipe/Widget"===b.widgetOnScreen.widgets[c].uri&&(a=!0);a||b.widgetOnScreen.widgets.push({uri:"widgets/Swipe/Widget",visible:!1,position:{top:145,left:7},version:"1.2"})}return b},compatible:!0},{version:"1.3",description:"The version embedded in online3.8.",upgrader:function(b){(function(c){h.visitElement(c,function(a){a.positionRelativeTo&&
(a.position?a.position.relativeTo=a.positionRelativeTo:a.position={relativeTo:a.positionRelativeTo},a.panel&&(a.panel.position?a.panel.position.relativeTo=a.panel.positionRelativeTo:a.panel.position={relativeTo:a.panel.positionRelativeTo}))});var a=c.widgetOnScreen;a&&(a.panel&&a.panel.positionRelativeTo)&&(a.panel.position?a.panel.position.relativeTo=a.panel.positionRelativeTo:a.panel.position={relativeTo:a.panel.positionRelativeTo});if((a=c.widgetPool)&&a.panel&&a.panel.positionRelativeTo)a.panel.position?
a.panel.position.relativeTo=a.panel.positionRelativeTo:a.panel.position={relativeTo:a.panel.positionRelativeTo}})(b);b.widgetOnScreen&&(b.widgetOnScreen.panel&&"jimu/PreloadWidgetIconPanel"===b.widgetOnScreen.panel.uri)&&(b.widgetOnScreen.panel.uri="jimu/OnScreenWidgetPanel");(function(c){if(c.widgetOnScreen&&c.widgetOnScreen.widgets&&c.theme&&"FoldableTheme"===c.theme.name){var a=null,b=null;void 0!==c.widgetOnScreen.widgets[4].position.top?(a={position:{left:205,top:45}},b={position:{left:255,top:45}}):
(a={position:{left:205,bottom:55}},b={position:{left:255,bottom:55}});c.widgetOnScreen.widgets.splice(7,0,a,b)}})(b);(function(){for(var c=0,a=0,d=!1,c=0;c<b.widgetOnScreen.widgets.length;c++)if("widgets/Geocoder/Widget"===b.widgetOnScreen.widgets[c].uri){d=!0;break}for(var e=!1,a=0;a<b.widgetOnScreen.widgets.length;a++)if("widgets/Search/Widget"===b.widgetOnScreen.widgets[a].uri){e=!0;break}!e&&d&&(c=b.widgetOnScreen.widgets[c],c.uri="widgets/Search/Widget",c.name="Search")})(b);(function(b){for(var a=
0,a=b.widgetOnScreen.widgets.length-1;0<=a;a--){var d=b.widgetOnScreen.widgets[a];if("widgets/Swipe/Widget"===d.uri&&!d.closeable&&(b.widgetOnScreen.widgets.splice(a,1),!1!==d.visible)){d.closeable=!0;var e;a:{for(e=e=0;e<b.widgetOnScreen.widgets.length;e++)if(!b.widgetOnScreen.widgets[e].uri)break a;e=-1}0<=e&&(d.position=b.widgetOnScreen.widgets[e].position,b.widgetOnScreen.widgets[e]=d)}"widgets/TimeSlider/Widget"===d.uri&&(!1===d.visible?b.widgetOnScreen.widgets.splice(a,1):d.closeable=!0)}})(b);
b.widgetOnScreen.widgets.push({uri:"widgets/ZoomSlider/Widget",position:{top:5,left:7},version:"1.3"});b.loadingPage||(b.loadingPage={backgroundColor:"#508dca",backgroundImage:{visible:!1},loadingGif:{visible:!0,uri:"configs/loading/images/predefined_loading_1.gif",width:58,height:58}});return b},compatible:!0}];this.isCompatible=function(b,c){for(var a=this.getVersionIndex(b),d=this.getVersionIndex(c),a=a+1;a<=d;a++)if(!1===this.versions[a].compatible)return!1;return!0}}f.prototype=new g;return f.prototype.constructor=
f});