//>>built
define({"widgets/Analysis/setting/nls/strings":{selectAnalysisTools:"Selecione ferramentas de an\u00e1lise para utilizar no widget.",selected:"selecionado",name:"Nome",graphicalDisplay:"Visualiza\u00e7\u00e3o gr\u00e1fica",usage:"Uso",settings:"Configura\u00e7\u00f5es",toolSetting:"Configurar detalhes da ferramenta",toolLabel:"O nome de visualiza\u00e7\u00e3o da ferramenta",showHelpTip:"Mostrar links de ajuda no widget",showCurrentMapExtent:"Mostrar op\u00e7\u00e3o para utilizar o mapa atual",showCredits:"Exibir a op\u00e7\u00e3o \x3cb\x3eMostrar cr\u00e9ditos\x3c/b\x3e",
saveAsFeatureService:"Salva o resultado na conta de usu\u00e1rio",showReadyToUseLayers:"Mostrar camadas prontas para uso de altas do mundo em tempo real do ArcGIS Online",toolNotAvailable:"Esta ferramenta n\u00e3o est\u00e1 dispon\u00edvel, pois o mapa n\u00e3o cont\u00e9m as camadas de fei\u00e7\u00e3o exigidas.",aggregatePoints:"Agregar Pontos",aggregatePointsUsage:"Agrega os pontos em pol\u00edgonos onde os pontos s\u00e3o localizados.",calculateDensity:"Calcular Densidade",calculateDensityUsage:"Cria um mapa de densidade a partir das fei\u00e7\u00f5es de ponto ou linha ao espalhar quantidades conhecidas de algum fen\u00f4meno (representados como atributos de pontos ou linhas) ao longo do mapa.",
connectOriginsToDestinations:"Conectar Origens aos Destinos",connectOriginsToDestinationsUsage:"Mede a dist\u00e2ncia ou tempo de percurso entre os pares de pontos.",createBuffers:"Criar Buffers",createBuffersUsage:"Cria pol\u00edgonos de buffer a partir das fei\u00e7\u00f5es de entrada.",createDriveTimeAreas:"Criar \u00c1reas de Tempo do Percurso",createDriveTimeAreasUsage:"Cria pol\u00edgonos de tempo do percurso (ou dist\u00e2ncia do percurso) ao redor dos pontos de entrada para os valores de tempo do percurso fornecidos.",
createViewshed:"Criar Panorama",createViewshedUsage:"Cria \u00e1reas que s\u00e3o vis\u00edveis baseadas em locais que voc\u00ea especifica.",createWatersheds:"Criar Vertentes",createWatershedsUsage:"Cria \u00e1reas de capta\u00e7\u00e3o baseadas em locais que voc\u00ea especifica.",deriveNewLocations:"Derivar Novos Locais",deriveNewLocationsUsage:"Deriva novas fei\u00e7\u00f5es a partir das camadas de entrada que atenderem uma consulta que voc\u00ea especificar",dissolveBoundaries:"Dissolver Limites",
dissolveBoundariesUsage:"Dissolve pol\u00edgonos que sobrep\u00f5em ou compartilham um limite em comum.",enrichLayer:"Enriquecer Camada",enrichLayerUsage:"Enriquece fei\u00e7\u00f5es de entrada com pessoas, lugares e fatos de neg\u00f3cios sobre \u00e1reas de proximidade.",extractData:"Extrair Dados",extractDataDesc:"Extrai dados de uma ou mais camadas dentro de uma extens\u00e3o fornecida",findExistingLocations:"Encontrar Locais Existentes",findExistingLocationsUsage:"Seleciona fei\u00e7\u00f5es na camada de entrada que atendem uma consulta de atributo e/ou espacial que voc\u00ea especificou",
findHotSpots:"Localizar Valor Alto de Incid\u00eancia",findHotSpotsUsage:"Localiza agrupamentos da fei\u00e7\u00e3o de entrada estat\u00edsticamente significativos ou valores altos/baixos.",findNearest:"Localizar Mais Pr\u00f3ximo",findNearestUsage:"Para cada fei\u00e7\u00e3o em uma camada de entrada, localize sua fei\u00e7\u00e3o mais pr\u00f3xima em outra camada",findSimilarLocations:"Encontrar Locais Semelhantes",findSimilarLocationsUsage:"Mede a semelhan\u00e7a de locais de candidatos para um ou mais locais de refer\u00eancia.",
interpolatePoints:"Interpolar Pontos",interpolatePointsUsage:"Prev\u00ea valores em novos locais baseado em medidas de uma coleta de pontos.",mergeLayers:"Juntar Camadas",mergeLayersUsage:"Junta as fei\u00e7\u00f5es de m\u00faltiplas camadas em uma nova camada",overlayLayers:"Sobrepor Camadas",overlayLayersUsage:"Combina m\u00faltiplas camadas em uma \u00fanica camada com informa\u00e7\u00f5es de camadas originais preservadas.",planRoutes:"Planejar Rotas",planRoutesUsage:"Determina como dividir eficazmente tarefas entre uma m\u00e3o-de-obra m\u00f3vel.",
summarizeNearby:"Resumir Mais Pr\u00f3ximo",summarizeNearbyUsage:"Para cada fei\u00e7\u00e3o em uma camada de entrada, resuma os dados dentro de uma dist\u00e2ncia das fei\u00e7\u00f5es em outra camada.",summarizeWithin:"Resumir Dentro",summarizeWithinUsage:"Para cada pol\u00edgono em uma camada de pol\u00edgono de entrada, resuma os dados localizados dentro dela a partir das fei\u00e7\u00f5es em outra camada.",traceDownstream:"Tra\u00e7ar Jusante",traceDownstreamUsage:"Determina os caminhos de fluxo em uma dire\u00e7\u00e3o da jusante a partir de locais que voc\u00ea especifica.",
_localized:{}}});