//>>built
define({"widgets/Analysis/setting/nls/strings":{selectAnalysisTools:"Seleccionar ferramentas de an\u00e1lise para usar no widget.",selected:"selecionadas",name:"Nome",graphicalDisplay:"Exibi\u00e7\u00e3o gr\u00e1fica",usage:"Utiliza\u00e7\u00e3o",settings:"Defini\u00e7\u00f5es",toolSetting:"Definir detalhes de ferramentas",toolLabel:"O nome de exibi\u00e7\u00e3o da ferramenta",showHelpTip:"Mostar links de ajuda no widget",showCurrentMapExtent:"Mostrar op\u00e7\u00e3o para usar no mapa actual",showCredits:"Exibir \x3cb\x3eMostrar cr\u00e9ditos\x3c/b\x3e",
saveAsFeatureService:"Guardar o resultado na conta user\u00e2\u20ac\u2122s",showReadyToUseLayers:"Mostar camadas prontas a usar a partir do living atlas ArcGIS Online do mundo",toolNotAvailable:"Esta ferramenta n\u00e3o se encontra dispon\u00edvel porque o mapa n\u00e3o cont\u00e9m a(s) camada(s) de elementos necess\u00e1ria(s).",aggregatePoints:"Pontos Agregados",aggregatePointsUsage:"Agregue pontos nos pol\u00edgonos em que os pontos est\u00e3o localizados.",calculateDensity:"Calcular Densidade",
calculateDensityUsage:"Crie um mapa de densidade a partir de elementos de ponto ou linha distribuindo quantidades conhecidas de determinado fen\u00f3meno(representado como atributos dos pontos ou linhas) pelo mapa.",connectOriginsToDestinations:"Ligar Origens a Destinos",connectOriginsToDestinationsUsage:"Me\u00e7a o tempo ou dist\u00e2ncia de viagem entre pares de pontos.",createBuffers:"Criar Buffers",createBuffersUsage:"Crie pol\u00edgonos de buffer a partir de elementos de entrada.",createDriveTimeAreas:"Criar \u00c1reas de Tempo de Condu\u00e7\u00e3o",
createDriveTimeAreasUsage:"Crie pol\u00edgonos de tempo de condu\u00e7\u00e3o (ou dist\u00e2ncia de condu\u00e7\u00e3o) \u00e0 volta de pontos de entrada para os valores de tempo de condu\u00e7\u00e3o.",createViewshed:"Criar Viewshed",createViewshedUsage:"Cria \u00e1reas que s\u00e3o vis\u00edveis com base em localiza\u00e7\u00f5es especificadas por si.",createWatersheds:"Criar Watersheds",createWatershedsUsage:"Cria \u00e1reas de capta\u00e7\u00e3o com base em localiza\u00e7\u00f5es especificadas por si.",
deriveNewLocations:"Derivar Novos locais",deriveNewLocationsUsage:"Derive novos elementos a partir das camadas de entrada que correspondam a umaconsulta especificada por si",dissolveBoundaries:"Dissolver Limites",dissolveBoundariesUsage:"Dissolva pol\u00edgonos que se sobreponham ou que partilhem um limite comum.",enrichLayer:"Enriquecer Camada",enrichLayerUsage:"Enrique\u00e7a elementos de entrada com factos sobre pessoas, locais e neg\u00f3cios em \u00e1reas aproximadas.",extractData:"Extrair Dados",
extractDataDesc:"Extraia dados de uma ou mais camadas dentro de uma determinada extens\u00e3o",findExistingLocations:"Encontrar Locais Existentes",findExistingLocationsUsage:"Selecione elementos na camada de entrada que correspondam a um atributo e/ou consulta espacial especificados por si.",findHotSpots:"Encontrar Hot Spots",findHotSpotsUsage:"Encontre clusters estatisticamente significativos de elementos de entrada ou de valores altos/baixos.",findNearest:"Localizar Pr\u00f3ximo",findNearestUsage:"Para cada elemento numa camada de entrada, encontre o respetivo elemento mais pr\u00f3ximo noutra camada.",
findSimilarLocations:"Encontrar Locais Semelhantes",findSimilarLocationsUsage:"Me\u00e7a a semelhan\u00e7a de locais candidados a uma ou mais localiza\u00e7\u00f5es de refer\u00eancia.",interpolatePoints:"Interpolar Pontos",interpolatePointsUsage:"Preveja valores em novos locais com base em medi\u00e7\u00f5es de uma cole\u00e7\u00e3o de pontos.",mergeLayers:"Juntar Camadas",mergeLayersUsage:"Junte elementos a partir de v\u00e1rias camadas numa nova camada.",overlayLayers:"Sobrepor Camadas",overlayLayersUsage:"Combine v\u00e1rias camadas numa \u00fanica camada garantindo a preserva\u00e7\u00e3o das informa\u00e7\u00f5es das camadas originais.",
planRoutes:"Planear Rotas",planRoutesUsage:"Determine como dividir as tarefas de uma for\u00e7a de trabalho m\u00f3vel de forma eficiente.",summarizeNearby:"Resumir Pr\u00f3ximo",summarizeNearbyUsage:"Por cada elemento numa camada de entrada, resuma dados a uma dist\u00e2ncia de elementos noutra camada.",summarizeWithin:"Resumir Dentro",summarizeWithinUsage:"Para cada pol\u00edgono numa camada de sa\u00edda, resuma dados localizados dentro da mesma com elementos noutra camada.",traceDownstream:"Trace Downstream",
traceDownstreamUsage:"Determine os caminhos dos fluxos numa dire\u00e7\u00e3o a jusante dos locais que especificou.",_localized:{}}});