//>>built
define({"widgets/Analysis/setting/nls/strings":{selectAnalysisTools:"Selezionare gli strumenti di analisi da utilizzare nel widget.",selected:"selezionato",name:"Nome",graphicalDisplay:"Visualizzazione grafica",usage:"Utilizzo",settings:"Impostazioni",toolSetting:"Imposta dettagli strumento",toolLabel:"Il nome visualizzato dello strumento",showHelpTip:"Mostra collegamenti della guida nel widget",showCurrentMapExtent:"Mostra opzione per utilizzare la mappa corrente",showCredits:"Visualizza l'opzione \x3cb\x3eMostra crediti\x3c/b\x3e",
saveAsFeatureService:"Salva il risultato nell'account dell'utente",showReadyToUseLayers:"Mostra layer pronti all'uso dall'atlante attivo del mondo di ArcGIS Online",toolNotAvailable:"Questo strumento non \u00e8 disponibile perch\u00e9 la mappa non contiene i feature layer richiesti.",aggregatePoints:"Aggrega punti",aggregatePointsUsage:"Aggrega i punti nei poligoni in cui si trovano tali punti.",calculateDensity:"Calcolo densit\u00e0",calculateDensityUsage:"Creare una mappa densit\u00e0 dalle feature puntuali o lineari distribuendo quantit\u00e0 conosciute di un fenomeno (rappresentato come attributi dei punti o delle linee) sulla mappa.",
connectOriginsToDestinations:"Connetti origini a destinazioni",connectOriginsToDestinationsUsage:"Consente di misurare la durata o la distanza del viaggio da coppie di punti.",createBuffers:"Crea buffer",createBuffersUsage:"Consente di creare poligoni buffer dalle feature di input.",createDriveTimeAreas:"Crea aree tempo di guida",createDriveTimeAreasUsage:"Consente di creare poligoni relativi al tempo di guida (o distanza di guida) attorno ai punti di input per i valori del tempo di guida specificati.",
createViewshed:"Crea campo di vista",createViewshedUsage:"Consente di creare aree visibili in base alle posizioni specificate.",createWatersheds:"Crea spartiacque",createWatershedsUsage:"Consente di creare aree di bacini fluviali in base alle posizioni specificate.",deriveNewLocations:"Deriva nuove localit\u00e0",deriveNewLocationsUsage:"Consente di derivare nuove feature in base ai layer di input conformi a una query specificata.",dissolveBoundaries:"Dissolvi confini",dissolveBoundariesUsage:"Consente di dissolvere i poligono che si sovrappongono o che condividono un confine comune.",
enrichLayer:"Aggiungi dati al layer",enrichLayerUsage:"Consente di aggiungere dati nelle feature di input, ovvero dati su persone, localit\u00e0 e attivit\u00e0 commerciali nelle aree vicine.",extractData:"Estrai dati",extractDataDesc:"Consente di estrarre i dati da uno o pi\u00f9 layer all'interno di un'estensione specificata.",findExistingLocations:"Trova localit\u00e0 esistenti",findExistingLocationsUsage:"Consente di selezionare le feature nel layer di input che soddisfa una query attributi e/o spaziale specificata.",
findHotSpots:"Trova hot spot",findHotSpotsUsage:"Consente di cercare cluster statisticamente significativi di feature di input o valori massimi/minimi.",findNearest:"Trova pi\u00f9 vicine",findNearestUsage:"Per ogni feature in un layer di input, consente di trovare la relativa feature pi\u00f9 vicina in un altro layer",findSimilarLocations:"Trova localit\u00e0 simili",findSimilarLocationsUsage:"Consente di misurare la somiglianza delle localit\u00e0 candidate rispetto a una o pi\u00f9 localit\u00e0 di riferimento.",
interpolatePoints:"Interpolazione punti",interpolatePointsUsage:"Consente di eseguire una previsione dei valori nelle nuove localit\u00e0 in base alle misurazioni provenienti da una raccolta di punti.",mergeLayers:"Unisci layer",mergeLayersUsage:"Consente di unire le feature da pi\u00f9 layer in un nuovo layer.",overlayLayers:"Sovrapponi layer",overlayLayersUsage:"Consente di combinare pi\u00f9 layer in un unico layer mantenendo inalterate le informazioni dei layer di origine.",planRoutes:"Pianifica itinerari",
planRoutesUsage:"Consente di definire come suddividere in modo efficiente le attivit\u00e0 tra gli addetti mobili.",summarizeNearby:"Riepiloga nelle vicinanze",summarizeNearbyUsage:"Per ogni feature in un layer di input, consente di riepilogare i dati all'interno di una distanza rispetto alle feature in un altro layer.",summarizeWithin:"Riepiloga entro",summarizeWithinUsage:"Per ogni poligono in un layer poligono di input, consente di riepilogare i dati che si trovano al suo interno rispetto alle feature in un altro layer.",
traceDownstream:"Traccia a valle",traceDownstreamUsage:"Consente di determinare i percorsi dei flussi nella direzione a valle dalle localit\u00e0 specificate.",_localized:{}}});