//>>built
define({"dgrid/extensions/nls/pagination":{status:"${start}\u2013${end}/${total} tulemust",gotoFirst:"Liigu esimesele lehele",gotoNext:"Liigu j\u00e4rgmisele lehele",gotoPrev:"Liigu eelmisele lehele",gotoLast:"Liigu viimasele lehele",gotoPage:"Liigu lehele",jumpPage:"H\u00fcppa lehele",rowsPerPage:"Number of rows per page",_localized:{}},"widgets/Analysis/setting/nls/strings":{selectAnalysisTools:"Vali anal\u00fc\u00fcsit\u00f6\u00f6riistad vidinas kasutamiseks.",selected:"valitud",name:"Nimi",graphicalDisplay:"Graafiline kuva",
usage:"Kasutus",settings:"Seaded",toolSetting:"Seadista t\u00f6\u00f6riista detailid",toolLabel:"T\u00f6\u00f6riista kuvanimi",showHelpTip:"N\u00e4ita vidinas spikri linke",showCurrentMapExtent:"N\u00e4ita praeguse kaardi kasutamise suvandit",showCredits:"Kuvamine\x3cb\x3eN\u00e4ita krediite\x3c/b\x3e suvand",saveAsFeatureService:"Salvesta tulemus kasutaj\u00e2\u20ac\u2122a kontos",showReadyToUseLayers:"N\u00e4ita kasutusvalmidusega kihte ArcGIS Online elukoha atlases",toolNotAvailable:"See t\u00f6\u00f6riist pole saadaval, kuna kaart ei sisalda n\u00f5utavaid objektikihte.",
aggregatePoints:"Agregeeri punktid",aggregatePointsUsage:"Agregeeri punktid pol\u00fcgoonideks, kus punktid asuvad.",calculateDensity:"Arvuta tihedus",calculateDensityUsage:"Punkt- v\u00f5i joonobjektidest tiheduskaardi loomiseks saate hajutada m\u00f5ne n\u00e4htuse teadaolevad hulgad (esitatud punktide v\u00f5i joonte atribuutidena) \u00fcle kogu kaardi.",connectOriginsToDestinations:"\u00dchenda algpunktid sihtpunktidega",connectOriginsToDestinationsUsage:"Saate m\u00f5\u00f5ta reisiaja v\u00f5i vahemaa punktipaaride vahel.",
createBuffers:"Loo puhvrid",createBuffersUsage:"Saate sisendobjektide p\u00f5hjal luua puhveralad.",createDriveTimeAreas:"Loo s\u00f5iduaja pinnad",createDriveTimeAreasUsage:"Saate etteantud s\u00f5iduaja v\u00e4\u00e4rtuste p\u00f5hjal luua sisendpunktide \u00fcmber s\u00f5iduaja (v\u00f5i s\u00f5iduvahemaa) pinnad.",createViewshed:"Loo vaatev\u00e4li",createViewshedUsage:"Loob alad, mis on teie m\u00e4\u00e4ratud asukohtadest n\u00e4htavad.",createWatersheds:"Loo valgalad",createWatershedsUsage:"Loob Teie m\u00e4\u00e4ratud asukohtadel p\u00f5hinevad valgalad.",
deriveNewLocations:"Tuleta uued asukohad",deriveNewLocationsUsage:"Saate tuletada uued objektid sisendkihtide p\u00f5hjal, mis vastavad Teie m\u00e4\u00e4ratud p\u00e4ringule.",dissolveBoundaries:"Sulanda piirid",dissolveBoundariesUsage:"Saate sulandada pol\u00fcgoonid, mis omavahel kattuvad v\u00f5i millel on \u00fchine piir.",enrichLayer:"Rikasta kihti",enrichLayerUsage:"Saate sisendobjekte rikastada teabega l\u00e4hedalasuvate alade ettev\u00f5tete, kohtade ja inimeste kohta.",extractData:"Andmete v\u00e4ljav\u00f5te",
extractDataDesc:"Saate andmed ekstraktida \u00fchest v\u00f5i mitmest teatud kindlas ulatuses asuvast kihist.",findExistingLocations:"Leia olemasolevad asukohad",findExistingLocationsUsage:"Saate sisendkihis valida objektid, mis vastavad Teie m\u00e4\u00e4ratud atribuudi- ja/v\u00f5i ruumilisele p\u00e4ringule.",findHotSpots:"Leia tulipunktid",findHotSpotsUsage:"Saate otsida sisendobjektide v\u00f5i suurte/v\u00e4ikeste v\u00e4\u00e4rtuste statistiliselt olulisi klastreid.",findNearest:"Leia l\u00e4him",
findNearestUsage:"Iga sisendkihil asuva objekti jaoks leitakse talle l\u00e4him objekt m\u00f5nel teisel kihil.",findSimilarLocations:"Leia sarnased asukohad",findSimilarLocationsUsage:"Saate m\u00f5\u00f5ta kandidaatasukohtade sarnasust \u00fche v\u00f5i mitme viiteasukohaga.",interpolatePoints:"Interpoleeri punktid",interpolatePointsUsage:"Saate prognoosida uute asukohtade v\u00e4\u00e4rtusi punktikogumike m\u00f5\u00f5tmiste p\u00f5hjal.",mergeLayers:"\u00dchenda kihid",mergeLayersUsage:"Saate mitme kihi objektid \u00fcheks uueks kihiks \u00fchendada",
overlayLayers:"Kattuvad kihid",overlayLayersUsage:"Saate mitu kihti \u00fchendada \u00fcheks kihiks nii, et algsete kihtide teave j\u00e4\u00e4b alles.",planRoutes:"Kavanda marsruudid",planRoutesUsage:"Saate m\u00e4\u00e4ratleda, kuidas \u00fclesanded v\u00e4lit\u00f6\u00f6tajate vahel efektiivselt jagada.",summarizeNearby:"Summeeri ligidusest",summarizeNearbyUsage:"Iga sisendkihil asuva objekti jaoks saate summeerida andmed, mis asuvad m\u00f5nel teisel kihil objektidest teatud raadiuses.",summarizeWithin:"Summeeri piirides",
summarizeWithinUsage:"Iga sisendpol\u00fcgoonkihil asuva pol\u00fcgooni jaoks saate summeerida andmed, mis asuvad m\u00f5nel teisel kihil objektidest selles raadiuses.",traceDownstream:"Allavoolu j\u00e4litus",traceDownstreamUsage:"Aitab m\u00e4\u00e4ratleda voolusuuna Teie m\u00e4\u00e4ratud asukohtades allavoolu suunas.",_localized:{}},"widgets/Analysis/nls/strings":{_widgetLabel:"Anal\u00fc\u00fcs",executeAnalysisTip:"Kl\u00f5psake k\u00e4ivitamiseks anal\u00fc\u00fcsi t\u00f6\u00f6riistale",noToolTip:"Anal\u00fc\u00fcsi t\u00f6\u00f6riista pole valitud!",
back:"Tagasi",next:"Edasi",home:"Avaleht",jobSubmitted:"esitatud.",jobCancelled:"T\u00fchistatud.",jobFailed:"Nurjus",jobSuccess:"Edukalt teostatud.",executing:"Teostamine",cancelJob:"T\u00fchista anal\u00fc\u00fcsi toiming",paramName:"Parameetri nimi",link:"Link",learnMore:"Lisateave",messages:"S\u00f5numid",outputs:"V\u00e4ljundid",outputtip:"M\u00e4rkus. Objekti- ja tabeliv\u00e4ljundid lisatakse kaardile t\u00f6\u00f6kihtidena.",outputSaveInPortal:"Andmed on salvestatud Teie portaali.",privilegeError:'Teie kasutajaroll ei saa anal\u00fc\u00fcsi teostada. Anal\u00fc\u00fcsi teostamiseks peab Teie asutuse administraator m\u00e4\u00e4rama Teile teatud \x3ca href\x3d"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm" target\x3d"_blank"\x3e\u00f5igused\x3c/a\x3e.',
_localized:{}}});