//>>built
define({"dgrid/extensions/nls/pagination":{status:"tulokset ${start} - ${end} / ${total}",gotoFirst:"Siirry ensimm\u00e4iselle sivulle",gotoNext:"Siirry seuraavalle sivulle",gotoPrev:"Siirry edelliselle sivulle",gotoLast:"Siirry viimeiselle sivulle",gotoPage:"Siirry sivulle",jumpPage:"Siirry sivulle",rowsPerPage:"Number of rows per page",_localized:{}},"widgets/Analysis/setting/nls/strings":{selectAnalysisTools:"Valitse pienoisohjelmassa k\u00e4ytett\u00e4v\u00e4t analyysity\u00f6kalut.",selected:"valittu",
name:"Nimi",graphicalDisplay:"Graafinen n\u00e4ytt\u00f6",usage:"K\u00e4ytt\u00f6",settings:"Settings",toolSetting:"M\u00e4\u00e4rit\u00e4 ty\u00f6kalun tiedot",toolLabel:"Ty\u00f6kalun n\u00e4ytt\u00f6nimi",showHelpTip:"N\u00e4yt\u00e4 ohjelinkit pienoisohjelmassa",showCurrentMapExtent:"N\u00e4yt\u00e4 vaihtoehto nykyisen kartan k\u00e4ytt\u00f6\u00e4 varten",showCredits:"N\u00e4yt\u00e4 \x3cb\x3eN\u00e4yt\u00e4 krediitit\x3c/b\x3e -vaihtoehto",saveAsFeatureService:"Tallenna tulos k\u00e4ytt\u00e4j\u00e4n tiliin",
showReadyToUseLayers:"N\u00e4yt\u00e4 ArcGIS Onlinen maailmankartaston k\u00e4ytt\u00f6valmiit karttatasot",toolNotAvailable:"T\u00e4m\u00e4 ty\u00f6kalu ei ole k\u00e4ytett\u00e4viss\u00e4, koska kartta ei sis\u00e4ll\u00e4 tarvittavia kohdekarttatasoja.",aggregatePoints:"Kokoa pisteet",aggregatePointsUsage:"Kokoa pisteet alueiksi, joissa pisteet sijaitsevat.",calculateDensity:"Laske tiheys",calculateDensityUsage:"Luo tiheyskartta piste- tai viivakohteista jakamalla tietyn ilmi\u00f6n tunnetut m\u00e4\u00e4r\u00e4t (esitet\u00e4\u00e4n pisteiden ja viivojen ominaisuustietoina) kartan alueelle.",
connectOriginsToDestinations:"Yhdist\u00e4 l\u00e4ht\u00f6pisteet m\u00e4\u00e4r\u00e4np\u00e4ihin",connectOriginsToDestinationsUsage:"Mittaa matkustusajan tai kahden pisteen v\u00e4linen et\u00e4isyys.",createBuffers:"Luo puskurit",createBuffersUsage:"Luo puskurialueet l\u00e4ht\u00f6aineiston kohteista.",createDriveTimeAreas:"Luo ajoaika-alueita",createDriveTimeAreasUsage:"Luo ajoaika-alueet (tai ajoet\u00e4isyysalueet) l\u00e4ht\u00f6pisteiden ymp\u00e4rille annettujen ajoaika-arvojen perusteella.",
createViewshed:"Luo n\u00e4kym\u00e4alue",createViewshedUsage:"Luo alueita, jotka n\u00e4kyv\u00e4t m\u00e4\u00e4ritt\u00e4miesi sijaintien perusteella.",createWatersheds:"Luo valuma-alueet",createWatershedsUsage:"Luo valuma-alueet m\u00e4\u00e4ritt\u00e4miesi sijaintien perusteella.",deriveNewLocations:"Laske uudet sijainnit",deriveNewLocationsUsage:"Johda uusia kohteita l\u00e4ht\u00f6aineiston karttatasoista, jotka t\u00e4ytt\u00e4v\u00e4t m\u00e4\u00e4ritt\u00e4m\u00e4si kyselyn",dissolveBoundaries:"Sulauta rajaukset",
dissolveBoundariesUsage:"Sulauta alueet, jotka ovat p\u00e4\u00e4llekk\u00e4isi\u00e4 tai joilla on yhteinen raja.",enrichLayer:"Rikasta karttataso",enrichLayerUsage:"Rikasta l\u00e4ht\u00f6aineiston kohteita l\u00e4hialueen ihmisten, paikkojen ja yritysten tiedoilla.",extractData:"Pura aineisto",extractDataDesc:"Pura aineisto yhdest\u00e4 tai useammasta karttatasosta annetun laajuuden rajoissa",findExistingLocations:"Hae nykyiset sijainnit",findExistingLocationsUsage:"Valitse l\u00e4ht\u00f6aineiston karttatason kohteet, jotka t\u00e4ytt\u00e4v\u00e4t m\u00e4\u00e4ritt\u00e4m\u00e4si ominaisuustiedon ja/tai sijaintikyselyn.",
findHotSpots:"Hae kuumat pisteet",findHotSpotsUsage:"Etsi tilastollisesti merkitsev\u00e4t l\u00e4ht\u00f6aineiston kohteiden tai pienten ja suurten arvojen keskittym\u00e4t.",findNearest:"Hae l\u00e4hin",findNearestUsage:"Etsi kullekin l\u00e4ht\u00f6aineiston karttatason kohteelle sen l\u00e4hdin kohde toisessa karttatasossa",findSimilarLocations:"Etsi samankaltaisia sijainteja",findSimilarLocationsUsage:"Vertaa ehdokassijaintien samankaltaisuutta v\u00e4hint\u00e4\u00e4n yhteen viitesijaintiin.",
interpolatePoints:"Interpoloi pisteet",interpolatePointsUsage:"Ennusta uusien sijaintien arvot ker\u00e4tyist\u00e4 pisteist\u00e4 l\u00f6ytyvien mittausten perusteella.",mergeLayers:"Yhdist\u00e4 karttatasot",mergeLayersUsage:"Yhdist\u00e4 usean karttatason kohteet uuteen karttatasoon",overlayLayers:"Kerrostasot",overlayLayersUsage:"Yhdist\u00e4 useita karttatasoja yhdeksi karttatasoksi, jossa alkuper\u00e4isten karttatasojen tiedot on s\u00e4ilytetty.",planRoutes:"Suunnittele reitit",planRoutesUsage:"M\u00e4\u00e4rit\u00e4, miten voit jakaa teht\u00e4vi\u00e4 tehokkaasti liikkuvalle ty\u00f6voimalle.",
summarizeNearby:"Yhteenveto, l\u00e4hist\u00f6",summarizeNearbyUsage:"Laadi aineiston yhteenveto kustakin l\u00e4ht\u00f6aineiston karttatason kohteesta, joka on tietyll\u00e4 et\u00e4isyydell\u00e4 toisen karttatason kohteista",summarizeWithin:"Yhteenveto alueella",summarizeWithinUsage:"Laadi aineiston yhteenveto kustakin l\u00e4ht\u00f6aineiston aluekarttatason alueesta, joka sijaitsee alueen rajoissa toisen karttatason kohteista.",traceDownstream:"J\u00e4ljit\u00e4 alavirtaan",traceDownstreamUsage:"M\u00e4\u00e4ritt\u00e4\u00e4 virtojen polut alavirran suunnassa m\u00e4\u00e4ritt\u00e4mist\u00e4si sijainneista.",
_localized:{}},"widgets/Analysis/nls/strings":{_widgetLabel:"Analyysi",executeAnalysisTip:"Suorita napsauttamalla analyysity\u00f6kalua",noToolTip:"Yht\u00e4\u00e4n analyysity\u00f6kalua ei ole valittu.",back:"Takaisin",next:"Seuraava",home:"Koti",jobSubmitted:"l\u00e4hetty.",jobCancelled:"Peruutettu.",jobFailed:"Ep\u00e4onnistui",jobSuccess:"Onnistui.",executing:"Suorittaa",cancelJob:"Peruuta analyysiteht\u00e4v\u00e4",paramName:"Parametrin nimi",link:"Linkki",learnMore:"Lis\u00e4tietoja",messages:"Viestit",
outputs:"Tulosaineistot",outputtip:"Huomautus: Kohteen ja taulun tulosaineistot lis\u00e4t\u00e4\u00e4n karttaan toiminnallisina karttatasoina.",outputSaveInPortal:"Aineisto on tallennettu portaaliin.",privilegeError:'K\u00e4ytt\u00e4j\u00e4roolisi ei voi suorittaa analyysia. Analyysin suoritus edellytt\u00e4\u00e4, ett\u00e4 organisaatiosi p\u00e4\u00e4k\u00e4ytt\u00e4j\u00e4 my\u00f6nt\u00e4\u00e4 sinulle tietyt \x3ca href\x3d"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm" target\x3d"_blank"\x3ek\u00e4ytt\u00f6oikeudet\x3c/a\x3e.',
_localized:{}}});