//>>built
define({"dgrid/extensions/nls/pagination":{status:"${start} - ${end} av ${total} resultater",gotoFirst:"G\u00e5 til f\u00f8rste side",gotoNext:"G\u00e5 til neste side",gotoPrev:"G\u00e5 til forrige side",gotoLast:"G\u00e5 til siste side",gotoPage:"G\u00e5 til side",jumpPage:"Hopp til side",rowsPerPage:"Number of rows per page",_localized:{}},"widgets/Analysis/setting/nls/strings":{selectAnalysisTools:"Velg analyseverkt\u00f8y som skal brukes i miniprogrammet.",selected:"valgte",name:"Navn",graphicalDisplay:"Grafisk visning",
usage:"Bruk",settings:"Innstillinger",toolSetting:"Angi verkt\u00f8ydetaljer",toolLabel:"Visningsnavnet for verkt\u00f8yet",showHelpTip:"Vis hjelpekoblinger i miniprogrammet",showCurrentMapExtent:"Vis alternativ for \u00e5 bruke det gjeldende kartet",showCredits:"Vis alternativet \x3cb\x3eVis credits\x3c/b\x3e",saveAsFeatureService:"Lagre resultatet i brukerens konto",showReadyToUseLayers:"Vis bruksklare lag fra det levende verdensatlaset p\u00e5 ArcGIS Online",toolNotAvailable:"Dette verkt\u00f8yet er ikke tilgjengelig fordi kartet ikke inneholder et eller flere n\u00f8dvendige geoobjektslag.",
aggregatePoints:"Samle punkter",aggregatePointsUsage:"Samle punkter i polygoner der punktene befinner seg.",calculateDensity:"Beregn tetthet",calculateDensityUsage:"Lag et tetthetskart fra punkt- eller linjegeoobjekter ved \u00e5 spre kjente mengder av et fenomen (vises som attributter for punktene eller linjene) over kartet.",connectOriginsToDestinations:"Koble startpunkter til destinasjoner",connectOriginsToDestinationsUsage:"Beregn reisetiden eller avstanden mellom to punkter.",createBuffers:"Opprett buffere",
createBuffersUsage:"Opprett bufferpolygoner fra inndatageoobjektene.",createDriveTimeAreas:"Opprett kj\u00f8retidsomr\u00e5der",createDriveTimeAreasUsage:"Opprett kj\u00f8retidspolygoner (eller kj\u00f8reavstand) rundt inndatapunktene for angitte kj\u00f8retidsverdier.",createViewshed:"Create Viewshed",createViewshedUsage:"Oppretter omr\u00e5der som er synlige basert p\u00e5 lokasjonene du angir.",createWatersheds:"Create Watersheds",createWatershedsUsage:"Oppretter nedb\u00f8rsfeltomr\u00e5der basert p\u00e5 lokasjonene du oppgir.",
deriveNewLocations:"Utled nye plasseringer",deriveNewLocationsUsage:"Utled nye geoobjekter fra inndatalagene som oppfyller en sp\u00f8rring du angir",dissolveBoundaries:"Visk ut grenser",dissolveBoundariesUsage:"L\u00f8s opp polygoner som overlapper eller deler en felles grense.",enrichLayer:"Suppleringsdata",enrichLayerUsage:"Berik inndatageoobjekter med fakta om mennesker, steder og bedrifter i n\u00e6rliggende omr\u00e5der.",extractData:"Ekstraher data",extractDataDesc:"Trekk ut data fra ett eller flere lag med en gitt utstrekning",
findExistingLocations:"Finn eksisterende plasseringer",findExistingLocationsUsage:"Velg geoobjekter i inndatalaget som oppfyller et attributt og/eller geografisk sp\u00f8rring du angir",findHotSpots:"Finn hotspots",findHotSpotsUsage:"Finn statistisk signifikante klynger med inndatageoobjekter eller h\u00f8ye/lave verdier.",findNearest:"Finn n\u00e6rmeste",findNearestUsage:"For hvert geoobjekt i et inndatalag finner du dets n\u00e6rmeste geoobjekt i et annet lag",findSimilarLocations:"Finn lignende lokasjoner",
findSimilarLocationsUsage:"M\u00e5l likheten mellom kandidatlokasjoner og to eller flere referanselokasjoner.",interpolatePoints:"Interpoler punkter",interpolatePointsUsage:"Forutsi verdier p\u00e5 nye lokasjoner basert p\u00e5 m\u00e5linger fra en samling punkter.",mergeLayers:"Sl\u00e5 sammen lag",mergeLayersUsage:"Sl\u00e5 sammen geoobjekter fra flere lag til et nytt lag.",overlayLayers:"Legg lag opp\u00e5",overlayLayersUsage:"Kombiner flere lag til ett enkelt lag der informasjonen fra de opprinnelige lagene beholdes.",
planRoutes:"Planlegg ruter",planRoutesUsage:"Finn ut hvordan du effektivt fordeler oppgaver i en mobil arbeidsstyrke.",summarizeNearby:"Summer n\u00e6rliggende",summarizeNearbyUsage:"For hvert geoobjekt i et inndatalaget summerer du data innenfor en avstand fra geoobjekter p\u00e5 et annet lag.",summarizeWithin:"Summer innenfor",summarizeWithinUsage:"For hvert polygon i et lagt med inndatapolygoner summerer du data som befinner seg i det fra geoobjekter i et annet lag.",traceDownstream:"Spor medstr\u00f8m",
traceDownstreamUsage:"Finner str\u00f8mningslinjene i nedstr\u00f8ms retning fra lokasjonene du oppgir.",_localized:{}},"widgets/Analysis/nls/strings":{_widgetLabel:"Analyse",executeAnalysisTip:"Klikk p\u00e5 et analyseverkt\u00f8y for \u00e5 utf\u00f8re",noToolTip:"Ingen analyseverkt\u00f8y er valgt",back:"Bak",next:"Neste",home:"Hjem",jobSubmitted:"sendt.",jobCancelled:"Avbrutt.",jobFailed:"Mislyktes",jobSuccess:"Vellykket.",executing:"Utf\u00f8rer",cancelJob:"Avbryt analyseoppgaven",paramName:"Parameternavn",
link:"Kobling",learnMore:"F\u00e5 mer informasjon",messages:"Meldinger",outputs:"Utdata",outputtip:"Merknad: Geoobjekts- og tabellutdata legges til som operative lag.",outputSaveInPortal:"Dataene er lagret i portalen.",privilegeError:'Brukerrollen din kan ikke utf\u00f8re analyser. Hvis du vil utf\u00f8re analyser, m\u00e5 administratoren i organisasjonen gi deg visse \x3ca href\x3d"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm" target\x3d"_blank"\x3erettigheter\x3c/a\x3e.',_localized:{}}});