//>>built
define({"dgrid/extensions/nls/pagination":{status:"${start} - ${end} din ${total} rezultate",gotoFirst:"Mergi la prima pagin\u0103",gotoNext:"Mergi la pagina urm\u0103toare",gotoPrev:"Mergi la pagina precedent\u0103",gotoLast:"Mergi la ultima pagin\u0103",gotoPage:"Mergi la pagina",jumpPage:"Sari la pagina",rowsPerPage:"Number of rows per page",_localized:{}},"widgets/Analysis/setting/nls/strings":{selectAnalysisTools:"Selecta\u0163i instrumentul de analiz\u0103 care va fi utilizat \u00een widget.",
selected:"selectat",name:"Nume",graphicalDisplay:"Afi\u015fare grafic\u0103",usage:"Utilizare",settings:"Set\u0103ri",toolSetting:"Setare detalii instrumente",toolLabel:"Setare nume afi\u015fat instrument",showHelpTip:"Afi\u015fare linkuri ajutor \u00een widget",showCurrentMapExtent:"Afi\u015fare op\u0163iune de utilizat \u00een harta curent\u0103",showCredits:"Afi\u015fare op\u0163iune \x3cb\x3eAfi\u015fare credite\x3c/b\x3e",saveAsFeatureService:"Salvare rezultat \u00een contul utilizatorului",
showReadyToUseLayers:"Afi\u015fare straturi tematice gata de utilizat din atlasul actualizat al lumii din ArcGIS Online",toolNotAvailable:"Acest instrument nu este disponibil deoarece harta nu con\u0163ine straturile tematice necesare.",aggregatePoints:"\u00censumare puncte",aggregatePointsUsage:"\u00censumare puncte \u00een poligoane acolo unde sunt localizate punctele.",calculateDensity:"Calcul densitate",calculateDensityUsage:"Crea\u0163i o hart\u0103 de densitate din obiecte spa\u0163iale punctuale sau liniare, r\u0103sp\u00e2ndind cantit\u0103\u0163i cunoscute ale unui anumit fenomen (reprezentate ca atribute ale punctelor sau liniilor) \u00een hart\u0103.",
connectOriginsToDestinations:"Conectare origini cu destina\u0163ii",connectOriginsToDestinationsUsage:"M\u0103sura\u0163i durata de c\u0103l\u0103torie sau distan\u0163a dintre perechi de puncte.",createBuffers:"Creare buffere",createBuffersUsage:"Creare poligoane buffer din obiecte spa\u0163iale introduse.",createDriveTimeAreas:"Creare suprafe\u0163e pentru timpul de conducere",createDriveTimeAreasUsage:"Crea\u0163i poligoane pentru timpul de condus (sau distan\u0163a de condus) \u00een jurul punctelor introduse pentru valorile date ale timpului de condus.",
createViewshed:"Creare raz\u0103 vizual\u0103",createViewshedUsage:"Creeaz\u0103 zone care sunt vizibile \u00een func\u0163ie de loca\u0163iile pe care le specifica\u0163i.",createWatersheds:"Creare cumpene de ape",createWatershedsUsage:"Creeaz\u0103 zone de captare \u00een func\u0163ie de loca\u0163iile pe care le specifica\u0163i.",deriveNewLocations:"Derivare loca\u0163ii noi",deriveNewLocationsUsage:"Deriva\u0163i obiecte spa\u0163iale noi din straturile tematice introduse care se potrivesc cu o interogare specificat\u0103",
dissolveBoundaries:"Dizolvare grani\u0163e",dissolveBoundariesUsage:"Dizolva\u0163i poligoanele care se suprapun sau au o grani\u0163\u0103 comun\u0103.",enrichLayer:"\u00cembog\u0103\u0163ire strat tematic",enrichLayerUsage:"\u00cembog\u0103\u0163i\u0163i obiectele spa\u0163iale introduse cu date despre persoane, locuri \u015fi companii din zonele din apropiere.",extractData:"Extragere date",extractDataDesc:"Extrage\u0163i date din unul sau mai multe straturi tematice \u00eentr-o anumit\u0103 m\u0103sur\u0103",
findExistingLocations:"G\u0103sire loca\u0163ii existente",findExistingLocationsUsage:"Selecta\u0163i obiecte spa\u0163iale din stratul tematic introdus care se potrivesc cu un atribut \u015fi/sau interogare spa\u0163ial\u0103 specificat\u0103 de dvs.",findHotSpots:"G\u0103sire puncte de interes",findHotSpotsUsage:"G\u0103si\u0163i grup\u0103ri de obiecte spa\u0163iale introduse sau valori ridicate/sc\u0103zute semnificative din punct de vedere statistic.",findNearest:"G\u0103sire cele mai apropiate",
findNearestUsage:"Pentru fiecare obiect spa\u0163ial dintr-un strat tematic introdus, g\u0103si\u0163i cel mai apropiat obiect spa\u0163ial de pe un alt strat tematic",findSimilarLocations:"G\u0103sire loca\u0163ii similare",findSimilarLocationsUsage:"M\u0103sura\u0163i gradul de similaritate al loca\u0163iilor candidate cu una sau mai multe loca\u0163ii de referin\u0163\u0103.",interpolatePoints:"Interpolare puncte",interpolatePointsUsage:"Prezice\u0163i valori \u00een loca\u0163ii noi pe baza m\u0103sur\u0103torilor dintr-o colec\u0163ie de puncte.",
mergeLayers:"Unificare straturi tematice",mergeLayersUsage:"Unifica\u0163i obiecte spa\u0163iale din straturi tematice multiple \u00eentr-un strat tematic nou",overlayLayers:"Suprapunere straturi tematice",overlayLayersUsage:"Combina\u0163i straturi tematice multiple \u00eentr-un singur strat tematic cu informa\u0163ii din straturile tematice originale conservate.",planRoutes:"Planificare rute",planRoutesUsage:"Determina\u0163i modul de alocare eficient\u0103 a opera\u0163iilor \u00een cadrul unei for\u0163e de munc\u0103 mobile.",
summarizeNearby:"Rezumat \u00een apropiere",summarizeNearbyUsage:"Pentru fiecare obiect spa\u0163ial dintr-un strat tematic introdus, rezuma\u0163i datele aflate la o anumit\u0103 distan\u0163\u0103 de obiectele spa\u0163iale din alt strat tematic.",summarizeWithin:"Rezumat \u00een",summarizeWithinUsage:"Pentru fiecare poligon dintr-un strat tematic cu poligoane, rezuma\u0163i datele aflate la distan\u0163a specificat\u0103 de obiectele spa\u0163iale dintr-un alt strat tematic.",traceDownstream:"Urm\u0103rire \u00een aval",
traceDownstreamUsage:"Determina\u0163i c\u0103ile de curgere \u00een aval din loca\u0163iile specificate de dvs.",_localized:{}},"widgets/Analysis/nls/strings":{_widgetLabel:"Analiz\u0103",executeAnalysisTip:"Face\u0163i clic pe un instrument de analiz\u0103 pentru a-l executa",noToolTip:"Nu a fost selectat niciun instrument de analiz\u0103!",back:"\u00cenapoi",next:"Urm\u0103tor",home:"Prima pagin\u0103",jobSubmitted:"trimis.",jobCancelled:"Anulat.",jobFailed:"E\u015fuat",jobSuccess:"Reu\u015fit.",
executing:"\u00cen curs de execu\u0163ie",cancelJob:"Anula\u0163i sarcina de analiz\u0103",paramName:"Nume parametru",link:"Link",learnMore:"Afla\u0163i mai multe",messages:"Mesaje",outputs:"Rezultate",outputtip:"Not\u0103: Rezultatele obiectelor spa\u0163iale \u015fi tabelelor sunt ad\u0103ugate la hart\u0103 sub form\u0103 de straturi tematice opera\u0163ionale.",outputSaveInPortal:"Datele au fost salvate la portalul dvs.",privilegeError:'Your user role cannot perform analysis. In order to perform analysis, the administrator of your organization needs to grant you certain \x3ca href"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm" target\x3d"_blank"\x3eprivileges\x3c/a\x3e.',
_localized:{}}});