//>>built
define({"dgrid/extensions/nls/pagination":{status:"${start} - ${end} av ${total} resultat",gotoFirst:"G\u00e5 till f\u00f6rsta sidan",gotoNext:"G\u00e5 till n\u00e4sta sida",gotoPrev:"G\u00e5 till f\u00f6reg\u00e5ende sida",gotoLast:"G\u00e5 till sista sidan",gotoPage:"G\u00e5 till sida",jumpPage:"Hoppa till sida",rowsPerPage:"Number of rows per page",_localized:{}},"widgets/Analysis/setting/nls/strings":{selectAnalysisTools:"V\u00e4lj vilka analysverktyg som ska anv\u00e4ndas i widgeten.",selected:"valt",
name:"Namn",graphicalDisplay:"Grafisk visning",usage:"Anv\u00e4ndning",settings:"Inst\u00e4llningar",toolSetting:"Ange verktygsinformation",toolLabel:"Verktygets visningsnamn",showHelpTip:"Visa hj\u00e4lpl\u00e4nkar i widgeten",showCurrentMapExtent:"Visa alternativ f\u00f6r att anv\u00e4nda den aktuella kartan",showCredits:"Visa alternativet \x3cb\x3eVisa krediter\x3c/b\x3e",saveAsFeatureService:"Visa resultatet i anv\u00e4ndarens konto",showReadyToUseLayers:"Visa lager som \u00e4r redo att anv\u00e4nda fr\u00e5n ArcGIS Onlines levande v\u00e4rldsatlas",
toolNotAvailable:"Det h\u00e4r verktyget \u00e4r inte tillg\u00e4ngligt eftersom kartan inte inneh\u00e5ller de geoobjektslager som kr\u00e4vs.",aggregatePoints:"Aggregera punkter",aggregatePointsUsage:"Aggregera punkterna till polygoner d\u00e4r punkterna \u00e4r placerade.",calculateDensity:"Ber\u00e4kna densitet",calculateDensityUsage:"Skapa en densitetskarta av punkt- eller linjegeoobjekt genom att sprida ut k\u00e4nda antal av n\u00e5got fenomen (som representeras som attribut f\u00f6r punkterna eller linjerna) \u00f6ver kartan.",
connectOriginsToDestinations:"Koppla startplatser till destinationer",connectOriginsToDestinationsUsage:"M\u00e4t restiden eller avst\u00e5ndet mellan punktpar.",createBuffers:"Skapa buffertar",createBuffersUsage:"Skapa buffertpolygoner av indatageoobjekt.",createDriveTimeAreas:"Skapa k\u00f6rtidsomr\u00e5den",createDriveTimeAreasUsage:"Skapa polygoner f\u00f6r k\u00f6rtid (eller k\u00f6ravst\u00e5nd) runt indatapunkter f\u00f6r de givna k\u00f6rtidsv\u00e4rdena.",createViewshed:"Skapa siktomr\u00e5de",
createViewshedUsage:"Skapar omr\u00e5den som \u00e4r synliga baserat p\u00e5 de platser du anger.",createWatersheds:"Skapa avrinningsomr\u00e5den",createWatershedsUsage:"Skapar uppsamlingsomr\u00e5den baserat p\u00e5 de platser du anger.",deriveNewLocations:"H\u00e4rled nya platser",deriveNewLocationsUsage:"H\u00e4rled nya geoobjekt fr\u00e5n de indatalager som motsvarar en fr\u00e5ga du anger",dissolveBoundaries:"L\u00f6s upp gr\u00e4nser",dissolveBoundariesUsage:"L\u00f6s upp polygoner som \u00f6verlappar eller delar en gemensam gr\u00e4ns.",
enrichLayer:"Berika lager",enrichLayerUsage:"Berika indatageoobjekten med m\u00e4nniskor, platser och f\u00f6retag i n\u00e4rliggande omr\u00e5den.",extractData:"Extrahera data",extractDataDesc:"Extrahera data fr\u00e5n ett eller flera lager inom en given utbredning",findExistingLocations:"Hitta befintliga platser",findExistingLocationsUsage:"V\u00e4lj geoobjekt i indatalagret som motsvarar ett attribut och/eller en geografisk fr\u00e5ga som du anger.",findHotSpots:"Hitta hotspots",findHotSpotsUsage:"S\u00f6k efter statistiskt signifikanta kluster av indatageoobjekt eller h\u00f6ga/l\u00e5ga v\u00e4rden.",
findNearest:"Hitta n\u00e4rmaste",findNearestUsage:"Hitta n\u00e4rmaste geoobjekt i ett annat lager f\u00f6r varje geoobjekt i ett indatalager",findSimilarLocations:"Hitta liknande platser",findSimilarLocationsUsage:"M\u00e4t kandidatplatsers likhet med en eller flera referensplatser.",interpolatePoints:"Interpoleringspunkter",interpolatePointsUsage:"F\u00f6ruts\u00e4g v\u00e4rden i nya platser baserat p\u00e5 m\u00e4tningar fr\u00e5n en samling punkter.",mergeLayers:"Sammanfoga lager",mergeLayersUsage:"Sl\u00e5 samman geoobjekt fr\u00e5n flera lager till ett nytt lager",
overlayLayers:"\u00d6verlagra lager",overlayLayersUsage:"Kombinera flera lager i ett enda lager med informationen bevarad fr\u00e5n ursprungslagren.",planRoutes:"Planera rutter",planRoutesUsage:"Fastst\u00e4ller hur du effektivt f\u00f6rdelar uppgifter inom en mobil arbetsstyrka.",summarizeNearby:"Summera n\u00e4ra",summarizeNearbyUsage:"Sammanfatta data inom en viss distans fr\u00e5n geoobjekt i ett annat lager f\u00f6r varje geoobjekt i ett indatalager.",summarizeWithin:"Summera inom",summarizeWithinUsage:"Sammanfatta data i ett indatapolygonlager fr\u00e5n geoobjekt i ett annat lager f\u00f6r varje polygon i ett annat lager.",
traceDownstream:"Sp\u00e5ra nedstr\u00f6ms",traceDownstreamUsage:"Avg\u00f6r fl\u00f6desm\u00f6nstren nedstr\u00f6ms fr\u00e5n de platser du anger.",_localized:{}},"widgets/Analysis/nls/strings":{_widgetLabel:"Analys",executeAnalysisTip:"Klicka p\u00e5 ett analysverktyg n\u00e4r du vill k\u00f6ra det",noToolTip:"Inget analysverktyg har valts.",back:"Tillbaka",next:"N\u00e4sta",home:"Hem",jobSubmitted:"skickades.",jobCancelled:"Avbr\u00f6ts.",jobFailed:"Misslyckades",jobSuccess:"Klart.",executing:"K\u00f6r",
cancelJob:"Avbryt analysen",paramName:"Parameternamn",link:"L\u00e4nk",learnMore:"L\u00e4r dig mer",messages:"Meddelanden",outputs:"Utdata",outputtip:"Obs! Geoobjektets och tabellens utdata har lagts till i kartan som operativa lager.",outputSaveInPortal:"Data har sparats i din portal.",privilegeError:'Din anv\u00e4ndarroll f\u00e5r inte utf\u00f6ra analyser. F\u00f6r att du ska kunna utf\u00f6ra analyser m\u00e5ste administrat\u00f6ren f\u00f6r din organisation bevilja dig vissa \x3ca href\x3d"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm" target\x3d"_blank"\x3ebeh\u00f6righeter\x3c/a\x3e.',
_localized:{}}});