//>>built
require({cache:{"url:widgets/Geoprocessing/setting/SettingDetail.html":'\x3cdiv\x3e\r\n\t\x3cdiv class\x3d"nav-pane jimu-float-leading" data-dojo-attach-point\x3d"navPaneNode"\x3e\x3c/div\x3e\r\n\t\x3cdiv class\x3d"setting-pane jimu-float-trailing" data-dojo-attach-point\x3d"settingPaneNode" style\x3d"display:none"\x3e\x3c/div\x3e\r\n\x3c/div\x3e\r\n'}});
define("dojo/_base/declare dojo/_base/lang dojo/_base/html dojo/_base/array dojo/on dojo/query dojo/text!./SettingDetail.html dijit/_WidgetBase dijit/_TemplatedMixin dijit/TitlePane jimu/dijit/ViewStack jimu/dijit/LoadingShelter jimu/dijit/Message ./ParamSetting ./LayerOrder ./Options ../utils".split(" "),function(h,d,b,g,f,k,l,m,n,p,q,r,s,t,u,v,e){return h([m,n],{baseClass:"jimu-widget-setting-gp-detail",templateString:l,postCreate:function(){this.inherited(arguments);this.paramSetting=new t({map:this.map,
nls:this.nls});this.layerOrder=new u({nls:this.nls});this.options=new v({nls:this.nls});this.viewStack=new q({viewType:"dijit",views:[this.paramSetting,this.layerOrder,this.options]},this.settingPaneNode);this.loadingCover=new r({hidden:!0});this.loadingCover.placeAt(this.domNode);this.loadingCover.startup()},startup:function(){this.inherited(arguments);this.viewStack.startup()},setConfig:function(a){a=d.clone(a);this.hasInputParam=!0;this.config&&this.config.taskUrl===a.taskUrl?(this.config=a,"serverInfo"in
a?this._initNavPane():(this.loadingCover.show(),e.getServiceDescription(this.config.taskUrl).then(d.hitch(this,function(a){this.loadingCover.hide();this.config.serverInfo=a.serverInfo;this._initNavPane()})))):(this.config=a,this.loadingCover.show(),e.getServiceDescription(this.config.taskUrl).then(d.hitch(this,function(a){this.loadingCover.hide();this._changeTaskInfoToConfig(a);this._initNavPane()})))},getConfig:function(){if(!this.config.taskUrl)return new s({message:this.nls.serviceURLPlaceholder}),
!1;this.paramSetting.param&&this.paramSetting.acceptValue();this.layerOrder.acceptValue();this.options.acceptValue();return this.config},_changeTaskInfoToConfig:function(a){var b=this.config.taskUrl;this.config=a;this.config.taskUrl=b;this.config.isSynchronous="esriExecutionTypeSynchronous"===this.config.executionType?!0:!1;delete this.config.executionType;this.config.inputParams=[];this.config.outputParams=[];g.forEach(a.parameters,function(a){a.label=a.displayName;delete a.displayName;"esriGPParameterDirectionInput"===
a.direction?this.config.inputParams.push(a):this.config.outputParams.push(a);delete a.direction;a.visible=!0;a.required="esriGPParameterTypeRequired"===a.parameterType?!0:!1;delete a.parameterType;"GPFeatureRecordSetLayer"===a.dataType&&(a.featureSetMode="draw")},this);this.config.shareResults=e.allowShareResult(this.config);delete this.config.parameters},_initNavPane:function(){b.empty(this.navPaneNode);this._createParamsSection("input");this._createParamsSection("output");this._createLayerOrderNode();
this._createOptionsNode();this.layerOrder.setConfig(this.config);this.options.setConfig(this.config);this.paramSetting.setConfig(this.config)},_onParamClick:function(a,d,c){this._setActiveLinkNode(c.currentTarget);this.paramSetting.param&&this.paramSetting.acceptValue();this.layerOrder.acceptValue();this.options.acceptValue();"none"===b.getStyle(this.viewStack.domNode,"display")&&b.setStyle(this.viewStack.domNode,"display","");this.viewStack.switchView(this.paramSetting);this.paramSetting.setParam(a,
d)},_setActiveLinkNode:function(a){k(".jimu-state-active",this.domNode).removeClass("jimu-state-active");b.addClass(a,"jimu-state-active")},_createParamsSection:function(a){var d=b.create("div",{"class":"nodes"});(new p({title:this.nls[a],content:d,open:"input"===a})).placeAt(this.navPaneNode);var c="input"===a?this.config.inputParams:this.config.outputParams;"input"===a&&0===c.length&&(this.hasInputParam=!1);g.forEach(c,function(b,c){var e=this._createParamLinkNode(b,a,d);(this.hasInputParam&&0===
c&&"input"===a||!1===this.hasInputParam&&0===c&&"output"===a)&&setTimeout(function(){e.click?e.click():f.emit(e,"click",{cancelable:!0,bubble:!0})},100)},this)},_createParamLinkNode:function(a,e,c){c=b.create("div",{"class":"link-action-node param-node"},c);b.create("div",{innerHTML:"\x3cspan\x3e"+this.nls.name+':\x3c/span\x3e\x3cspan style\x3d"margin-left: 2px" title\x3d"'+a.name+'"\x3e'+a.name+"\x3c/span\x3e"},c);b.create("div",{innerHTML:"\x3cspan\x3e"+this.nls.type+':\x3c/span\x3e\x3cspan style\x3d"margin-left: 2px" title\x3d"'+
a.dataType+'"\x3e'+a.dataType+"\x3c/span\x3e"},c);b.create("div",{innerHTML:"\x3cspan\x3e"+this.nls.required+':\x3c/span\x3e\x3cspan style\x3d"margin-left: 2px"\x3e'+a.required+"\x3c/span\x3e"},c);this.own(f(c,"click",d.hitch(this,this._onParamClick,a,e)));return c},_createLayerOrderNode:function(){var a=b.create("div",{"class":"link-action-node nav-pane-node layer-order-node",innerHTML:this.nls.layerOrder},this.navPaneNode);this.own(f(a,"click",d.hitch(this,function(){this.options.acceptValue();
this.paramSetting.param&&this.paramSetting.acceptValue();this._setActiveLinkNode(a);this.layerOrder.setConfig(this.config);this.viewStack.switchView(this.layerOrder)})))},_createOptionsNode:function(){var a=b.create("div",{"class":"link-action-node nav-pane-node options-node",innerHTML:this.nls.options},this.navPaneNode);this.own(f(a,"click",d.hitch(this,function(){this.paramSetting.param&&this.paramSetting.acceptValue();this.layerOrder.acceptValue();this._setActiveLinkNode(a);this.viewStack.switchView(this.options)})))}})});