//>>built
require({cache:{"libs/usng/usng":function(){window.console||(window.console={warn:function(){}});define(["dojo/_base/declare","dojo/string"],function(s,c){var p,l,q,m=Math.PI/180,h=180/Math.PI,k,g;k=6378137;g=0.006694380023;var t=g/(1-g),n=(1-Math.sqrt(1-g))/(1+Math.sqrt(1-g));return{getZoneNumber:function(a,b){a=parseFloat(a);b=parseFloat(b);(360<b||-180>b||90<a||-90>a)&&console.warn("Bad input. lat: "+a+" lon: "+b);var f=b+180-360*parseInt((b+180)/360)-180,e=parseInt((f+180)/6)+1;56<=a&&(64>a&&
3<=f&&12>f)&&(e=32);72<=a&&84>a&&(0<=f&&9>f?e=31:9<=f&&21>f?e=33:21<=f&&33>f?e=35:33<=f&&42>f&&(e=37));return e},LLtoUTM:function(a,b,f,e){a=parseFloat(a);b=parseFloat(b);if(84<a||-80>a)return"undefined";(360<b||-180>b||90<a||-90>a)&&console.warn("Bad input. lat: "+a+" lon: "+b);var d=b+180-360*parseInt((b+180)/360)-180,c=a*m,d=d*m;q=e?e:this.getZoneNumber(a,b);var h=(6*(q-1)-180+3)*m;this.UTMLetterDesignator(a);a=k/Math.sqrt(1-g*Math.sin(c)*Math.sin(c));b=Math.tan(c)*Math.tan(c);e=t*Math.cos(c)*
Math.cos(c);d=Math.cos(c)*(d-h);h=k*((1-g/4-3*g*g/64-5*g*g*g/256)*c-(3*g/8+3*g*g/32+45*g*g*g/1024)*Math.sin(2*c)+(15*g*g/256+45*g*g*g/1024)*Math.sin(4*c)-35*g*g*g/3072*Math.sin(6*c));p=0.9996*a*(d+(1-b+e)*d*d*d/6+(5-18*b+b*b+72*e-58*t)*d*d*d*d*d/120)+5E5;l=0.9996*(h+a*Math.tan(c)*(d*d/2+(5-b+9*e+4*e*e)*d*d*d*d/24+(61-58*b+b*b+600*e-330*t)*d*d*d*d*d*d/720));f[0]=p;f[1]=l;f[2]=q},LLtoUSNG:function(a,b,f){a=parseFloat(a);b=parseFloat(b);var e=[];this.LLtoUTM(a,b,e);var d=e[0],e=e[1];0>a&&(e+=1E7);var c=
this.findGridLetters(q,e,d),e=Math.round(e)%1E5,d=Math.round(d)%1E5,e=Math.floor(e/Math.pow(10,5-f)),d=Math.floor(d/Math.pow(10,5-f));a=this.getZoneNumber(a,b)+this.UTMLetterDesignator(a)+" "+c+" ";for(b=String(d).length;b<f;b++)a+="0";a+=d+" ";for(b=String(e).length;b<f;b++)a+="0";return a+e},UTMLetterDesignator:function(a){a=parseFloat(a);return 84>=a&&72<=a?"X":72>a&&64<=a?"W":64>a&&56<=a?"V":56>a&&48<=a?"U":48>a&&40<=a?"T":40>a&&32<=a?"S":32>a&&24<=a?"R":24>a&&16<=a?"Q":16>a&&8<=a?"P":8>a&&0<=
a?"N":0>a&&-8<=a?"M":-8>a&&-16<=a?"L":-16>a&&-24<=a?"K":-24>a&&-32<=a?"J":-32>a&&-40<=a?"H":-40>a&&-48<=a?"G":-48>a&&-56<=a?"F":-56>a&&-64<=a?"E":-64>a&&-72<=a?"D":-72>a&&-80<=a?"C":"Z"},findSet:function(a){a=parseInt(a);switch(a%6){case 0:return 6;case 1:return 1;case 2:return 2;case 3:return 3;case 4:return 4;case 5:return 5;default:return-1}},findGridLetters:function(a,b,f){a=parseInt(a);b=parseFloat(b);f=parseFloat(f);var e=1;for(b=Math.round(b);1E5<=b;)b-=1E5,e++;e%=20;b=0;for(f=Math.round(f);1E5<=
f;)f-=1E5,b++;return this.lettersHelper(this.findSet(a),e,b%8)},lettersHelper:function(a,b,f){0===b?b=19:b--;0===f?f=7:f--;switch(a){case 1:return a="ABCDEFGHJKLMNPQRSTUV","ABCDEFGH".charAt(f)+a.charAt(b);case 2:return a="FGHJKLMNPQRSTUVABCDE","JKLMNPQR".charAt(f)+a.charAt(b);case 3:return a="ABCDEFGHJKLMNPQRSTUV","STUVWXYZ".charAt(f)+a.charAt(b);case 4:return a="FGHJKLMNPQRSTUVABCDE","ABCDEFGH".charAt(f)+a.charAt(b);case 5:return a="ABCDEFGHJKLMNPQRSTUV","JKLMNPQR".charAt(f)+a.charAt(b);case 6:return a=
"FGHJKLMNPQRSTUVABCDE","STUVWXYZ".charAt(f)+a.charAt(b)}},UTMtoLL:function(a,b,f,e){b=parseFloat(b)-5E5;a=parseFloat(a);f=6*(parseInt(f)-1)-180+3;a=a/0.9996/(k*(1-g/4-3*g*g/64-5*g*g*g/256));a=a+(3*n/2-27*n*n*n/32)*Math.sin(2*a)+(21*n*n/16-55*n*n*n*n/32)*Math.sin(4*a)+151*n*n*n/96*Math.sin(6*a);var d=k/Math.sqrt(1-g*Math.sin(a)*Math.sin(a)),c=Math.tan(a)*Math.tan(a),m=t*Math.cos(a)*Math.cos(a),l=k*(1-g)/Math.pow(1-g*Math.sin(a)*Math.sin(a),1.5);b/=0.9996*d;d=a-d*Math.tan(a)/l*(b*b/2-(5+3*c+10*m-4*
m*m-9*t)*b*b*b*b/24+(61+90*c+298*m+45*c*c-252*t-3*m*m)*b*b*b*b*b*b/720);d*=h;b=(b-(1+2*c+m)*b*b*b/6+(5-2*m+28*c-3*m*m+8*t+24*c*c)*b*b*b*b*b/120)/Math.cos(a);b=f+b*h;e.lat=d;e.lon=b},USNGtoUTM:function(a,b,f,e,d,c,g){f=1+"ABCDEFGHJKLMNPQRSTUVWXYZ".indexOf(f)%8;var m="CDEFGHJKLMNPQRSTUVWX".indexOf(b);e=a%2?"ABCDEFGHJKLMNPQRSTUV".indexOf(e):"FGHJKLMNPQRSTUVABCDE".indexOf(e);e=Number([0,2,2,2,4,4,6,6,8,8,0,0,0,2,2,4,4,6,6,6][m])+e/10;e<[1.1,2,2.9,3.8,4.7,5.6,6.5,7.3,8.2,9.1,0,0.8,1.7,2.6,3.5,4.4,5.3,
6.2,7,7.9][m]&&(e+=2);g.N=1E6*e+Number(c)*Math.pow(10,5-c.length);g.E=1E5*f+Number(d)*Math.pow(10,5-d.length);g.zone=a;g.letter=b},USNGtoLL:function(a,b){var f={};this.parseUSNG_str(a,f);var e={};this.USNGtoUTM(f.zone,f.let,f.sq1,f.sq2,f.east,f.north,e);"N">f.let&&(e.N-=1E7);this.UTMtoLL(e.N,e.E,f.zone,e);b[0]=e.lat;b[1]=e.lon},parseUSNG_str:function(a,b){var f=0,e,d=[];e=[];e=a.toUpperCase();d=/%20/g;e.replace(d,"");d=/ /g;d=e.replace(d,"");if(7>d.length)return console.warn("This application requires minimum USNG precision of 10,000 meters"),
0;b.zone=10*d.charAt(f++)+1*d.charAt(f++);b.let=d.charAt(f++);b.sq1=d.charAt(f++);b.sq2=d.charAt(f++);b.precision=(d.length-f)/2;b.east="";b.north="";for(e=0;e<b.precision;e++)b.east+=d.charAt(f++);" "==d[f]&&f++;for(e=0;e<b.precision;e++)b.north+=d.charAt(f++)},isUSNG:function(a){var b=[],b=a.toUpperCase();a=/%20/g;b=b.replace(a,"");a=/ /g;b=b.replace(a,"");if(15<b.length)return 0;a=/^[0-9]{2}[CDEFGHJKLMNPQRSTUVWX]$/;if(b.match(a))return console.warn("Input appears to be a UTM zone...more precision is required to display a correct result."),
0;a=/^[0-9]{2}[CDEFGHJKLMNPQRSTUVWX][ABCDEFGHJKLMNPQRSTUVWXYZ][ABCDEFGHJKLMNPQRSTUV]([0-9][0-9]){0,5}/;return!b.match(a)?0:7>b.length?(alert(b+" Appears to be a USNG string, but this application requires precision of at least 10,000 meters"),0):b},LLtoMGRS:function(a,b,f){var e="";return e=this.LLtoUSNG(a,b,f).replace(/ /g,"")},LLtoUSNG_nad27:function(a,b,f){k=6378206.4;g=0.006768658;a=this.LLtoUSNG(a,b,f);k=6378137;g=0.006694380023;return a+" (NAD27)"}}})},"dojo/string":function(){define(["./_base/kernel",
"./_base/lang"],function(s,c){var p=/[&<>'"\/]/g,l={"\x26":"\x26amp;","\x3c":"\x26lt;","\x3e":"\x26gt;",'"':"\x26quot;","'":"\x26#x27;","/":"\x26#x2F;"},q={};c.setObject("dojo.string",q);q.escape=function(c){return!c?"":c.replace(p,function(c){return l[c]})};q.rep=function(c,h){if(0>=h||!c)return"";for(var k=[];;){h&1&&k.push(c);if(!(h>>=1))break;c+=c}return k.join("")};q.pad=function(c,h,k,g){k||(k="0");c=String(c);h=q.rep(k,Math.ceil((h-c.length)/k.length));return g?c+h:h+c};q.substitute=function(m,
h,k,g){g=g||s.global;k=k?c.hitch(g,k):function(c){return c};return m.replace(/\$\{([^\s\:\}]+)(?:\:([^\s\:\}]+))?\}/g,function(m,l,a){m=c.getObject(l,!1,h);a&&(m=c.getObject(a,!1,g).call(g,m,l));return k(m,l).toString()})};q.trim=String.prototype.trim?c.trim:function(c){c=c.replace(/^\s+/,"");for(var h=c.length-1;0<=h;h--)if(/\S/.test(c.charAt(h))){c=c.substring(0,h+1);break}return c};return q})},"libs/storejs/json":function(){define(["dojo","dijit","dojox"],function(s,c,p){this.JSON||(this.JSON=
{});(function(){function c(b){return 10>b?"0"+b:b}function q(b){k.lastIndex=0;return k.test(b)?'"'+b.replace(k,function(b){var a=n[b];return"string"===typeof a?a:"\\u"+("0000"+b.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+b+'"'}function m(b,f){var c,d,h,k,l=g,n,r=f[b];r&&("object"===typeof r&&"function"===typeof r.toJSON)&&(r=r.toJSON(b));"function"===typeof a&&(r=a.call(f,b,r));switch(typeof r){case "string":return q(r);case "number":return isFinite(r)?String(r):"null";case "boolean":case "null":return String(r);
case "object":if(!r)return"null";g+=p;n=[];if("[object Array]"===Object.prototype.toString.apply(r)){k=r.length;for(c=0;c<k;c+=1)n[c]=m(c,r)||"null";h=0===n.length?"[]":g?"[\n"+g+n.join(",\n"+g)+"\n"+l+"]":"["+n.join(",")+"]";g=l;return h}if(a&&"object"===typeof a){k=a.length;for(c=0;c<k;c+=1)d=a[c],"string"===typeof d&&(h=m(d,r))&&n.push(q(d)+(g?": ":":")+h)}else for(d in r)Object.hasOwnProperty.call(r,d)&&(h=m(d,r))&&n.push(q(d)+(g?": ":":")+h);h=0===n.length?"{}":g?"{\n"+g+n.join(",\n"+g)+"\n"+
l+"}":"{"+n.join(",")+"}";g=l;return h}}"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(b){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+c(this.getUTCMonth()+1)+"-"+c(this.getUTCDate())+"T"+c(this.getUTCHours())+":"+c(this.getUTCMinutes())+":"+c(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(b){return this.valueOf()});var h=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
k=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,g,p,n={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},a;"function"!==typeof JSON.stringify&&(JSON.stringify=function(b,c,e){var d;p=g="";if("number"===typeof e)for(d=0;d<e;d+=1)p+=" ";else"string"===typeof e&&(p=e);if((a=c)&&"function"!==typeof c&&("object"!==typeof c||"number"!==typeof c.length))throw Error("JSON.stringify");return m("",{"":b})});
"function"!==typeof JSON.parse&&(JSON.parse=function(b,a){function c(b,d){var g,h,k=b[d];if(k&&"object"===typeof k)for(g in k)Object.hasOwnProperty.call(k,g)&&(h=c(k,g),void 0!==h?k[g]=h:delete k[g]);return a.call(b,d,k)}var d;b=String(b);h.lastIndex=0;h.test(b)&&(b=b.replace(h,function(b){return"\\u"+("0000"+b.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(b.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return d=eval("("+b+")"),"function"===typeof a?c({"":d},""):d;throw new SyntaxError("JSON.parse");})})()})},"dijit/main":function(){define(["dojo/_base/kernel"],function(s){return s.dijit})},"dojox/main":function(){define(["dojo/_base/kernel"],function(s){return s.dojox})},"libs/storejs/store":function(){(function(s){var c={},p=s.document,l;c.disabled=!1;c.set=function(b,a){};c.get=function(b){};c.remove=function(b){};c.clear=function(){};c.transact=function(b,
a,e){var d=c.get(b);null==e&&(e=a,a=null);"undefined"==typeof d&&(d=a||{});e(d);c.set(b,d)};c.getAll=function(){};c.forEach=function(){};c.serialize=function(b){return JSON.stringify(b)};c.deserialize=function(b){if("string"==typeof b)try{return JSON.parse(b)}catch(a){return b||void 0}};var q;try{q="localStorage"in s&&s.localStorage}catch(m){q=!1}if(q)l=s.localStorage,c.set=function(b,a){if(void 0===a)return c.remove(b);l.setItem(b,c.serialize(a));return a},c.get=function(b){return c.deserialize(l.getItem(b))},
c.remove=function(b){l.removeItem(b)},c.clear=function(){l.clear()},c.getAll=function(){var b={};c.forEach(function(a,c){b[a]=c});return b},c.forEach=function(b){for(var a=0;a<l.length;a++){var e=l.key(a);b(e,c.get(e))}};else if(p.documentElement.addBehavior){var h,k;try{k=new ActiveXObject("htmlfile"),k.open(),k.write('\x3cscript\x3edocument.w\x3dwindow\x3c/script\x3e\x3ciframe src\x3d"/favicon.ico"\x3e\x3c/iframe\x3e'),k.close(),h=k.w.frames[0].document,l=h.createElement("div")}catch(g){l=p.createElement("div"),
h=p.body}var p=function(b){return function(){var a=Array.prototype.slice.call(arguments,0);a.unshift(l);h.appendChild(l);l.addBehavior("#default#userData");l.load("localStorage");a=b.apply(c,a);h.removeChild(l);return a}},t=RegExp("[!\"#$%\x26'()*+,/\\\\:;\x3c\x3d\x3e?@[\\]^`{|}~]","g"),n=function(b){return b.replace(/^d/,"___$\x26").replace(t,"___")};c.set=p(function(b,a,e){a=n(a);if(void 0===e)return c.remove(a);b.setAttribute(a,c.serialize(e));b.save("localStorage");return e});c.get=p(function(b,
a){a=n(a);return c.deserialize(b.getAttribute(a))});c.remove=p(function(b,a){a=n(a);b.removeAttribute(a);b.save("localStorage")});c.clear=p(function(b){var a=b.XMLDocument.documentElement.attributes;b.load("localStorage");for(var c=0,d;d=a[c];c++)b.removeAttribute(d.name);b.save("localStorage")});c.getAll=function(a){var f={};c.forEach(function(a,b){f[a]=b});return f};c.forEach=p(function(a,f){for(var e=a.XMLDocument.documentElement.attributes,d=0,g;g=e[d];++d)f(g.name,c.deserialize(a.getAttribute(g.name)))})}try{c.set("__storejs__",
"__storejs__"),"__storejs__"!=c.get("__storejs__")&&(c.disabled=!0),c.remove("__storejs__")}catch(a){c.disabled=!0}c.enabled=!c.disabled;"undefined"!=typeof module&&module.exports&&this.module!==module?module.exports=c:"function"===typeof define&&define.amd?define(c):s.store=c})(Function("return this")())}}});define(["./usng/usng","./storejs/json","./storejs/store"],function(){});