//>>built
define({"dijit/_editor/nls/commands":{bold:"Bold",copy:"Copy",cut:"Cut","delete":"Delete",indent:"Indent",insertHorizontalRule:"Horizontal Rule",insertOrderedList:"Numbered List",insertUnorderedList:"Bullet List",italic:"Italic",justifyCenter:"Align Center",justifyFull:"Justify",justifyLeft:"Align Left",justifyRight:"Align Right",outdent:"Outdent",paste:"Paste",redo:"Redo",removeFormat:"Remove Format",selectAll:"Select All",strikethrough:"Strikethrough",subscript:"Subscript",superscript:"Superscript",
underline:"Underline",undo:"Undo",unlink:"Remove Link",createLink:"Create Link",toggleDir:"Toggle Direction",insertImage:"Insert Image",insertTable:"Insert/Edit Table",toggleTableBorder:"Toggle Table Border",deleteTable:"Delete Table",tableProp:"Table Property",htmlToggle:"HTML Source",foreColor:"Foreground Color",hiliteColor:"Background Color",plainFormatBlock:"Paragraph Style",formatBlock:"Paragraph Style",fontSize:"Font Size",fontName:"Font Name",tabIndent:"Tab Indent",fullScreen:"Toggle Full Screen",
viewSource:"View HTML Source",print:"Print",newPage:"New Page",systemShortcut:'The "${0}" action is only available in your browser using a keyboard shortcut. Use ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{ar:1,az:1,bg:1,ca:1,cs:1,da:1,de:1,el:1,es:1,et:1,fi:1,fr:1,he:1,hr:1,hu:1,id:1,it:1,ja:1,kk:1,ko:1,lt:1,lv:1,nb:1,nl:1,pl:1,pt:1,"pt-pt":1,ro:1,ru:1,sk:1,sl:1,sv:1,th:1,tr:1,uk:1,vi:1,zh:1,"zh-hk":1,"zh-tw":1}},"dijit/_editor/nls/FontChoice":{1:"xx-small",2:"x-small",3:"small",
4:"medium",5:"large",6:"x-large",7:"xx-large",fontSize:"Size",fontName:"Font",formatBlock:"Format",serif:"serif","sans-serif":"sans-serif",monospace:"monospace",cursive:"cursive",fantasy:"fantasy",noFormat:"None",p:"Paragraph",h1:"Heading",h2:"Subheading",h3:"Sub-subheading",pre:"Pre-formatted",_localized:{ar:1,az:1,bg:1,ca:1,cs:1,da:1,de:1,el:1,es:1,et:1,fi:1,fr:1,he:1,hr:1,hu:1,id:1,it:1,ja:1,kk:1,ko:1,lt:1,lv:1,nb:1,nl:1,pl:1,pt:1,"pt-pt":1,ro:1,ru:1,sk:1,sl:1,sv:1,th:1,tr:1,uk:1,vi:1,zh:1,"zh-hk":1,
"zh-tw":1}},"dojox/editor/plugins/nls/Preview":{preview:"Preview",_localized:{ar:1,bg:1,ca:1,cs:1,da:1,de:1,el:1,es:1,fi:1,fr:1,he:1,hr:1,hu:1,id:1,it:1,ja:1,kk:1,ko:1,nb:1,nl:1,pl:1,pt:1,"pt-pt":1,ro:1,ru:1,sk:1,sl:1,sv:1,th:1,tr:1,uk:1,zh:1,"zh-hk":1,"zh-tw":1}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Find:",findTooltip:"Enter text to find",replaceLabel:"Replace with:",replaceTooltip:"Enter text to replace with",findReplace:"Find and Replace",matchCase:"Match case",matchCaseTooltip:"Match case",
backwards:"Backwards",backwardsTooltip:"Search backwards for text",replaceAllButton:"Replace All",replaceAllButtonTooltip:"Replace all the text",findButton:"Find",findButtonTooltip:"Find the text",replaceButton:"Replace",replaceButtonTooltip:"Replace the text",replaceDialogText:"Replaced ${0} occurrences.",eofDialogText:"Last occurrence ${0}",eofDialogTextFind:"found",eofDialogTextReplace:"replaced",_localized:{ar:1,bg:1,ca:1,cs:1,da:1,de:1,el:1,es:1,fi:1,fr:1,he:1,hr:1,hu:1,id:1,it:1,ja:1,kk:1,ko:1,
nb:1,nl:1,pl:1,pt:1,"pt-pt":1,ro:1,ru:1,sk:1,sl:1,sv:1,th:1,tr:1,uk:1,zh:1,"zh-hk":1,"zh-tw":1}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Paste From Word",instructions:"Paste the content from Word into the text box below.  Once you are satisfied with the content to insert, press the paste button.  To abort inserting text, press the cancel button.",_localized:{ar:1,bg:1,ca:1,cs:1,da:1,de:1,el:1,es:1,fi:1,fr:1,he:1,hr:1,hu:1,id:1,it:1,ja:1,kk:1,ko:1,nb:1,nl:1,pl:1,pt:1,"pt-pt":1,ro:1,
ru:1,sk:1,sl:1,sv:1,th:1,tr:1,uk:1,zh:1,"zh-hk":1,"zh-tw":1}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Insert Anchor",title:"Anchor Properties",anchor:"Name:",text:"Description:",set:"Set",cancel:"Cancel",_localized:{ar:1,bg:1,ca:1,cs:1,da:1,de:1,el:1,es:1,fi:1,fr:1,he:1,hr:1,hu:1,id:1,it:1,ja:1,kk:1,ko:1,nb:1,nl:1,pl:1,pt:1,"pt-pt":1,ro:1,ru:1,sk:1,sl:1,sv:1,th:1,tr:1,uk:1,zh:1,"zh-hk":1,"zh-tw":1}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blockquote",_localized:{ar:1,bg:1,
ca:1,cs:1,da:1,de:1,el:1,es:1,fi:1,fr:1,he:1,hr:1,hu:1,id:1,it:1,ja:1,kk:1,ko:1,nb:1,nl:1,pl:1,pt:1,"pt-pt":1,ro:1,ru:1,sk:1,sl:1,sv:1,th:1,tr:1,uk:1,zh:1,"zh-hk":1,"zh-tw":1}},"widgets/About/setting/nls/strings":{instruction:"Create the content that displays in this widget.",defaultContent:"Add text, links, and small graphics here.",_localized:{ar:1,cs:1,da:1,de:1,el:1,es:1,et:1,fi:1,fr:1,he:1,it:1,ja:1,ko:1,lt:1,lv:1,nb:1,nl:1,pl:1,"pt-br":1,"pt-pt":1,ro:1,ru:1,sv:1,th:1,tr:1,vi:1,"zh-cn":1,"zh-hk":1,
"zh-tw":1}}});