//>>built
define("dojo/_base/declare dojo/_base/html dijit/_WidgetBase dgrid/OnDemandGrid dgrid/Selection dgrid/extensions/ColumnHider dgrid/extensions/ColumnResizer dojo/Deferred dojo/Evented dojo/store/Memory esri/request esri/tasks/RelationshipQuery dojo/_base/lang dojo/on dojo/_base/array jimu/dijit/LoadingIndicator ./utils".split(" "),function(k,e,m,n,p,q,r,s,t,u,v,w,f,x,l,y,h){return k([m,t],{baseClass:"jimu-widget-attributetable-relationship-table",_defaultFeatureCount:2E3,_defaultBatchCount:25,_batchCount:0,
relationship:null,parentWidget:null,noGridHeight:0,footerHeight:25,loading:null,grid:null,footer:null,selectedRowsLabel:null,selectionRows:null,nls:null,constructor:function(a){a=a||{};this.set("relationship",a.relationship||null);this.parentWidget=a.parentWidget||null;this.noGridHeight=a.noGridHeight||0},postCreate:function(){this.selectionRows=[];this.loading=new y;this.loading.placeAt(this.domNode)},startQuery:function(a,c){var b=this.relationship;if(b&&!b.opened&&c&&0<c.length){this.loading.show();
var d=new w;d.objectIds=c;d.outFields=["*"];d.relationshipId=b.id;d.returnGeometry=!1;if(a.url){var g=a.url.split("/");g[g.length-1]=b.relatedTableId;g=g.join("/");v({url:g,content:{f:"json"},hangleAs:"json",callbackParamName:"callback"}).then(f.hitch(this,function(c){this.domNode&&a.queryRelatedFeatures(d,f.hitch(this,function(a){if(this.domNode){var d={displayFieldName:b.objectIdField,fields:c.fields,features:[],fieldAliases:null},g;for(g in a){var f=a[g];f.features&&0<f.features.length&&(d.features=
d.features.concat(f.features))}0<d.features.length?(this.createTable(c,d),this.emit("data-loaded")):(a=e.toDom("\x3cdiv\x3e"+this.nls.noRelatedRecords+"\x3c/div\x3e"),e.empty(this.domNode),e.place(a,this.domNode),e.place(this.loading.domNode,this.domNode));b.opened=!0;this.loading.hide()}}),f.hitch(this,function(a){console.error(a);a=e.toDom("\x3cdiv\x3e"+this.nls.noRelatedRecords+"\x3c/div\x3e");e.empty(this.domNode);e.place(a,this.domNode);e.place(this.loading.domNode,this.domNode);this.loading.hide()}))}),
f.hitch(this,function(a){console.error(a);this.loading.hide()}))}}else this.loading.hide()},getSelectedRows:function(){return this.selectionRows},zoomTo:function(){},showSelectedRecords:function(){var a=this.relationship.objectIdField;this.grid._clickShowSelectedRecords=!0;var c=this._getSelectedIds();0<c.length&&this.grid&&this.grid.set("query",f.hitch(this,function(b){return"number"===typeof b&&-1<c.indexOf(b)||-1<c.indexOf(b[a])?!0:!1}))},clearSelection:function(){this.grid.clearSelection();this.selectionRows=
[];this.grid.set("query",{});this.setSelectedNumber();this.emit("clear-selection")},exportToCSV:function(){return this._getExportData().then(f.hitch(this,function(a){if(this.domNode)return h.createCSVStr(a.data,a.outFields,a.pk,a.types)}))},toggleColumns:function(){this.grid&&this.grid._toggleColumnHiderMenu()},changeHeight:function(a){this.grid&&0<=a-this.noGridHeight-this.footerHeight&&e.setStyle(this.grid.domNode,"height",a-this.noGridHeight-this.footerHeight+"px")},destroy:function(){this.parentWidget=
this.configedInfo=this.layerInfo=null;this.grid&&this.grid.destroy();this.nls=this.map=null;this.relationship.opened=!1;this.relationship=null;this.inherited(arguments)},createTable:function(a,c){var b=l.map(c.features,f.hitch(this,function(a){return a.attributes})),d=h.generateMemoryStore(b,c.displayFieldName),g=h.generateColumnsFromFields(c.fields,a.typeIdField,a.types);this.grid?(this.grid.set("store",d),this.grid.refresh()):(d={columns:g,store:d},this.grid=new (k([n,p,q,r]))(d,e.create("div")),
e.place(this.grid.domNode,this.domNode),this.grid.startup(),this.grid.__pk=c.displayFieldName,this.grid.__outFields=c.fields,this.own(x(this.grid,".dgrid-row:click",f.hitch(this,this._onRowClick))));this.footer?e.empty(this.footer):this.footer=e.create("div",null,this.domNode);b=e.create("div",{"class":"dgrid-status self-footer",innerHTML:b.length+"\x26nbsp;"+this.nls.features+"\x26nbsp;"},this.footer);this.selectedRowsLabel=e.create("div",{"class":"dgrid-status self-footer",innerHTML:"0\x26nbsp;"+
this.nls.selected+"\x26nbsp;"},b,"after");b=e.getStyle(this.parentWidget.domNode,"height");this.changeHeight(b)},_getExportData:function(){if(this.relationship){var a=new s,c=this.grid.__outFields,b=this.relationship.objectIdField,d=this.getSelectedRowsData();d&&0<d.length?a.resolve({data:d,outFields:c,pk:b,types:null}):(d=this.grid.store,d instanceof u?(d=d.data,a.resolve({data:d,outFields:c,pk:b,types:null})):a.resolve({data:[],outFields:c,pk:b,types:null}));return a}},getSelectedRowsData:function(){if(!this.grid)return null;
var a=this.relationship.objectIdField,c=this.grid.store,b=c._entityData||c.data,c=this.getSelectedRows();return l.map(c,f.hitch(this,function(c){for(var e=0,f=b.length;e<f;e++)if(b[e]&&b[e][a]===c)return b[e];return{}}))||[]},setSelectedNumber:function(){if(this.selectedRowsLabel&&this.grid){var a=this.getSelectedRows();this.selectedRowsLabel.innerHTML="\x26nbsp;\x26nbsp;"+a.length+" "+this.nls.selected+"\x26nbsp;\x26nbsp;"}},_onRowClick:function(){this.selectionRows=this._getSelectedIds();this.setSelectedNumber();
this.emit("row-click",{table:this,selectedIds:f.clone(this.selectionRows)})},_getSelectedIds:function(){var a=[],c=this.grid.selection,b;for(b in c)c[b]&&(isFinite(b)?a.push(parseInt(b,10)):a.push(b));return a}})});