//>>built
define("dojo/_base/lang dojo/_base/array jimu/LayerInfos/LayerInfos dojo/Deferred dojo/promise/all exports dojo/store/Observable dojo/store/Cache dojo/store/Memory esri/lang ./FeatureLayerQueryStore jimu/utils".split(" "),function(g,l,u,r,s,e,z,A,v,w,B,x){function C(a){var b=[],c=[];l.forEach(a,function(d){var h=b.indexOf(d.name);0>h?b.push(d.name):(c.push(a[h]),c.push(d))});l.forEach(c,function(a){a.name=a.name+"-"+a.id})}e.readLayerInfosObj=function(a){return u.getInstance(a,a.itemInfo)};e.readLayerInfosFromMap=
function(a){var b=new r;u.getInstance(a,a.itemInfo).then(g.hitch(this,function(a){var d=[];a.traversal(g.hitch(this,function(a){d.push(a)}));a=a.getTableInfoArray();d=d.concat(a);b.resolve(d)}),g.hitch(this,function(a){console.error(a);b.reject(a)}));return b.promise};e.createCSVStr=function(a,b,c,d){var h=new r,f="",g=0,k=0,n="",m="";try{l.forEach(b,function(a){f=f+n+(a.alias||a.name);n=","});for(var f=f+"\r\n",g=a.length,k=b.length,q=0;q<g;q++){for(var n="",t=0;t<k;t++){var y=b[t],m=e.getExportValue(a[q][y.name],
y,c,a[q][c],d);!m&&"number"!==typeof m&&(m="");m&&/[",]/g.test(m)&&(m='"'+m.replace(/(")/g,'""')+'"');f=f+n+m;n=","}f+="\r\n"}h.resolve(f)}catch(D){console.error(D),h.resolve("")}return h};e.getExportValue=function(a,b,c,d,h){var f=!!b.domain,g="esriFieldTypeDate"===b.type,k=c&&b.name===c;return g?e.dateFormatter(a):f?e.getCodeValue(b.domain,a):!f&&!g&&!k?(f=null,c&&h&&0<h.length&&(c=l.filter(h,function(a){return a.name===d}))&&(c.domains&&c.domains[b.name]&&c.domains[b.name].codedValues)&&(f=e.getCodeValue(c.domains[b.name],
a)),null!==f?f:a):a};e.generateColumnsFromFields=function(a,b,c,d){var h={};l.forEach(a,g.hitch(e,function(f,p){var k="field"+p,n=!!f.domain,m="esriFieldTypeDate"===f.type,q=b&&f.name===b;h[k]={label:f.alias||f.name,className:k,hidden:!f.show&&w.isDefined(f.show),unhidable:!f.show&&w.isDefined(f.show)&&f._pk,field:f.name};h[k].sortable=!!d;if("esriFieldTypeString"===a[p].type)h[k].formatter=g.hitch(e,e.urlFormatter);else if("esriFieldTypeDate"===a[p].type)h[k].formatter=g.hitch(e,e.dateFormatter);
else if("esriFieldTypeDouble"===a[p].type||"esriFieldTypeSingle"===a[p].type||"esriFieldTypeInteger"===a[p].type||"esriFieldTypeSmallInteger"===a[p].type)h[k].formatter=g.hitch(e,e.numberFormatter);n?h[k].get=g.hitch(e,function(a,b){return this.getCodeValue(a.domain,b[a.name])},f):q?h[k].get=g.hitch(e,function(a,b,d){return this.getTypeName(d[a.name],b)},f,c):!n&&(!m&&!q)&&(h[k].get=g.hitch(e,function(a,b,d,c){var f=null;b&&d&&0<d.length&&(d=l.filter(d,g.hitch(e,function(a){return a.name===c[b]})))&&
(d.domains&&d.domains[a.name]&&d.domains[a.name].codedValues)&&(f=this.getCodeValue(d.domains[a.name],c[a.name]));return(a=null!==f?f:c[a.name])||isFinite(a)?a:""},f,b,c))}));return h};e.getTypeName=function(a,b){for(var c=b.length,d=0;d<c;d++)if(a===b[d].id)return b[d].name;return a};e.getCodeValue=function(a,b){if(a.codedValues){for(var c=0,d=a.codedValues.length;c<d;c++){var h=a.codedValues[c];if(b===h.code)return h.name}return b}return b||null};e.urlFormatter=function(a){if(a&&"string"===typeof a){var b=
a.indexOf("http:");-1===b&&(b=a.indexOf("https:"));if(-1<b&&-1===a.indexOf("href\x3d")){var c=a.indexOf(" ",b);-1===c&&(c=a.length);var d=a.substring(b,c);a=a.substring(0,b)+'\x3cA href\x3d"'+d+'" target\x3d"_blank"\x3e'+d+"\x3c/A\x3e"+a.substring(c,a.length)}}return a||""};e.dateFormatter=function(a){a&&(a=x.localizeDate(new Date(a),{fullYear:!0}));return a||""};e.numberFormatter=function(a){if("number"===typeof a){var b=(a.toString().split(".")[1]||"").length;a=x.localizeNumber(a,{places:b});return'\x3cspan class\x3d"jimu-numeric-value"\x3e'+
(a||"")+"\x3c/span\x3e"}return a};e.readLayerObjectsFromMap=function(a){var b=new r,c=[];this.readLayerInfosFromMap(a).then(g.hitch(this,function(a){l.forEach(a,g.hitch(this,function(a){c.push(a.getLayerObject())}));s(c).then(g.hitch(this,function(a){b.resolve(a)}),g.hitch(this,function(a){b.reject(a);console.error(a)}))}),g.hitch(this,function(a){b.reject(a)}));return b.promise};e.readSupportTableInfoFromLayerInfos=function(a){var b=new r,c=[];l.forEach(a,g.hitch(this,function(a){c.push(a.getSupportTableInfo())}));
s(c).then(g.hitch(this,function(d){d=g.clone(d);l.forEach(d,function(b,d){b.id=a[d].id});b.resolve(d)}),function(a){b.reject(a)});return b.promise};e.readConfigLayerInfosFromMap=function(a){var b=new r,c=[];this.readLayerInfosFromMap(a).then(g.hitch(this,function(a){var e=[];l.forEach(a,function(a){c.push(a.getSupportTableInfo())});s(c).then(g.hitch(this,function(c){l.forEach(c,g.hitch(this,function(b,c){b.isSupportedLayer&&(a[c].name=a[c].title,e.push(a[c]))}));C(e);b.resolve(e)}),g.hitch(this,function(a){b.reject(a)}))}),
g.hitch(this,function(a){b.reject(a)}));return b.promise};e.getConfigInfosFromLayerInfos=function(a){return l.map(a,function(a){return e.getConfigInfoFromLayerInfo(a)})};e.getConfigInfoFromLayerInfo=function(a){var b={};b.name=a.name||a.title;b.id=a.id;b.show=a.isShowInMap();b.layer={url:a.getUrl()};if((a=a.getPopupInfo())&&!a.description)b.layer.fields=l.map(a.fieldInfos,function(a){return{name:a.fieldName,alias:a.label.toLowerCase(),show:a.visible}});return b};e.generateCacheStore=function(a,b,
c,d){a=new B({layer:a,objectIds:a._objectIds||null,totalCount:b,batchCount:c,where:d||"1\x3d1"});b=new v;return new A(a,b,{})};e.generateMemoryStore=function(a,b){return new z(new v({data:a||[],idProperty:b}))}});