//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/html dojo/on dojo/Deferred dojo/promise/all dojo/json dijit/form/NumberTextBox dijit/form/Select dijit/form/Textarea dijit/form/DateTextBox dijit/form/TimeTextBox jimu/dijit/CheckBox jimu/dijit/URLInput jimu/dijit/DrawBox esri/SpatialReference esri/tasks/LinearUnit esri/tasks/FeatureSet esri/tasks/query esri/tasks/QueryTask esri/request esri/geometry/Polygon esri/graphic esri/graphicsUtils ../BaseEditor ../LayerOrderUtil".split(" "),
function(e,k,f,c,n,s,t,p,u,m,v,w,x,y,q,z,A,B,C,D,E,F,G,r,H,g,I){var d={};d.UnsupportEditor=e(g,{baseClass:"jimu-gp-editor-base jimu-gp-editor-unsupport",editorName:"UnsupportEditor",postCreate:function(){this.inherited(arguments);c.setAttr(this.domNode,"innerHTML",this.message)},getValue:function(){return null}});d.ShowMessage=e(g,{baseClass:"jimu-gp-editor-base jimu-gp-editor-message",editorName:"ShowMessage",postCreate:function(){this.inherited(arguments);c.setAttr(this.domNode,"innerHTML",this.message)},
getValue:function(){return null}});d.GeneralEditorWrapperEditor=e(g,{baseClass:"jimu-gp-editor-base jimu-gp-editor-wrapper",editorName:"GeneralEditorWrapperEditor",postCreate:function(){this.inherited(arguments);c.setStyle(this.gEditor.domNode,"width","100%");this.gEditor.placeAt(this.domNode)},getValue:function(){return this.gEditor.getValue()}});d.MultiValueChooser=e(g,{baseClass:"jimu-gp-editor-base jimu-gp-editor-multivalue-chooser",editorName:"MultiValueChooser",postCreate:function(){this.inherited(arguments);
this.checkBoxs=[];f.forEach(this.param.choiceList,function(a){a=new y({label:a,checked:this.param.defaultValue&&-1<this.param.defaultValue.indexOf(a)?!0:!1});a.placeAt(this.domNode);this.checkBoxs.push(a)},this)},getValue:function(){var a=[];f.forEach(this.checkBoxs,function(b){b.checked&&a.push(b.label)},this);return a}});d.MultiValueEditor=e(g,{baseClass:"jimu-gp-editor-base jimu-gp-editor-multivalue",editorName:"MultiValueEditor",postCreate:function(){this.inherited(arguments);this.editors=[];
var a=c.create("div",{"class":"input-list"},this.domNode),b=k.clone(this.param,a);b.dataType=this.param.dataType.substr(13,this.param.dataType.length);b.originParam=this.param;setTimeout(k.hitch(this,this._initChildEditors,b,a),100);this._createAddInputNode(b,a)},_initChildEditors:function(a,b){this.param.defaultValue&&0<this.param.defaultValue.length?f.forEach(this.param.defaultValue,function(h){a.defaultValue=h;this._createSingleInputContainerNode(a,b)},this):(delete a.defaultValue,this._createSingleInputContainerNode(a,
b))},getValue:function(){var a=[];f.forEach(this.editors,function(b){a.push(b.getValue())},this);return a},getGPValue:function(){var a=new s,b=[];f.forEach(this.editors,function(a){b.push(a.getGPValue())},this);t(b).then(function(b){a.resolve(b)},function(b){a.reject(b)});return a},destroy:function(){f.forEach(this.editors,function(a){a.destroy()});this.editors=[];this.inherited(arguments)},_createSingleInputContainerNode:function(a,b){var h=c.create("div",{"class":"single-input"},b),l=this.editorManager.createEditor(a,
"input",this.context,{widgetUID:this.widgetUID,config:this.config}),d=c.getContentBox(this.domNode).w-30-3;c.setStyle(l.domNode,{display:"inline-block",width:d+"px"});l.placeAt(h);this._createRemoveInputNode(h);h.inputEditor=l;this.editors.push(l);return h},_createRemoveInputNode:function(a){var b=c.create("div",{"class":"remove",innerHTML:"-"},a);this.own(n(b,"click",k.hitch(this,function(){this.editors.splice(this.editors.indexOf(a.inputEditor),1);a.inputEditor.destroy();c.destroy(a)})));return b},
_createAddInputNode:function(a,b){var h=c.create("div",{"class":"add-input"},this.domNode),l=c.create("div",{"class":"add-btn",innerHTML:"+"},h);this.own(n(l,"click",k.hitch(this,function(){this._createSingleInputContainerNode(a,b)})));return h}});d.LinerUnitEditor=e(g,{baseClass:"jimu-gp-editor-base jimu-gp-editor-liner-unit",editorName:"LinerUnitEditor",postCreate:function(){this.inherited(arguments);this.distance=void 0===this.param.defaultValue?"":this.param.defaultValue.distance;this.units=void 0===
this.param.defaultValue?"":this.param.defaultValue.units;void 0===this.distance&&(this.distance=0);void 0===this.units&&(this.units="esriMeters");this.inputDijit=new u({value:this.distance});this.selectDijit=new m({value:this.units,options:[{label:"Meters",value:"esriMeters"},{label:"Kilometers",value:"esriKilometers"},{label:"Feet",value:"esriFeet"},{label:"Miles",value:"esriMiles"},{label:"NauticalMiles",value:"esriNauticalMiles"},{label:"Yards",value:"esriYards"}]});this.inputDijit.placeAt(this.domNode);
this.selectDijit.placeAt(this.domNode)},getValue:function(){var a=new B;a.distance=this.inputDijit.getValue();a.units=this.selectDijit.getValue();return a}});d.DateTimeEditor=e(g,{baseClass:"jimu-gp-editor-base jimu-gp-editor-datatime",editorName:"DateTimeEditor",postCreate:function(){var a=new Date,b=new Date(this.param.defaultValue);this.value=this.param.defaultValue?new Date(b.getFullYear(),b.getMonth(),b.getDate(),b.getHours(),b.getMinutes(),b.getSeconds()):new Date(a.getFullYear(),a.getMonth(),
a.getDate(),a.getHours(),a.getMinutes(),a.getSeconds());this.inherited(arguments);this.dateDijit=new w({value:this.value,style:{width:"60%"}});this.timeDijit=new x({value:this.value,style:{width:"40%"},constraints:{timePattern:"HH:mm:ss",clickableIncrement:"T00:15:00",visibleIncrement:"T00:15:00"}});this.dateDijit.placeAt(this.domNode);this.timeDijit.placeAt(this.domNode)},startup:function(){this.dateDijit.startup();this.timeDijit.startup()},getValue:function(){var a=new Date,b=this.dateDijit.getValue(),
c=this.timeDijit.getValue();a.setFullYear(b.getFullYear());a.setMonth(b.getMonth());a.setDate(b.getDate());a.setHours(c.getHours());a.setMinutes(c.getMinutes());a.setSeconds(c.getSeconds());return a.getTime()}});d.SelectFeatureSetFromDraw=e([g,z],{editorName:"SelectFeatureSetFromDraw",constructor:function(a){this.inherited(arguments);this.paramName=a.param.name;this.drawLayerId=a.widgetUID+a.param.name},postCreate:function(){this.inherited(arguments);c.addClass(this.domNode,"jimu-gp-editor-draw");
c.addClass(this.domNode,"jimu-gp-editor-base");try{(new I(this.config,this.map)).calculateLayerIndex(this.paramName,this.widgetUID).then(k.hitch(this,function(a){-1!==a&&this.map.reorderLayer(this.drawLayer,a)}))}catch(a){console.error(a.message)}this.startup()},getValue:function(){return this.drawLayer&&0<this.drawLayer.graphics.length?this._createFeatureSet(this.drawLayer.graphics):null},_createFeatureSet:function(a){var b=new C,c=[];a=H.getGeometries(a);f.forEach(a,function(a){a="extent"===a.type?
new r(G.fromExtent(a)):new r(a);c.push(a)});b.features=c;return b}});d.GetUrlObjectFromLayer=e([g,m],{editorName:"GetUrlObjectFromLayer",postCreate:function(){this.options=[];f.forEach(this.map.graphicsLayerIds,function(a){a=this.map.getLayer(a);if("esri.layers.FeatureLayer"===a.declaredClass&&(!this.geometryType||a.geometryType===this.geometryType))this.options.push({label:a.label||a.title||a.name||a.id,value:a.id})},this);this.inherited(arguments);this.setValue(this.value);c.addClass(this.domNode,
"jimu-gp-editor-sffl");c.addClass(this.domNode,"jimu-gp-editor-base")},getValue:function(){return this.value},getGPValue:function(){var a,b;f.forEach(this.map.graphicsLayerIds,function(b){var c=this.map.getLayer(b);b===this.getValue()&&(a=c.url)},this);b={url:a};b=this.wrapGPValue(b);return this.wrapValueToDeferred(b)}});d.SelectFeatureSetFromUrl=e([g,q],{editorName:"SelectFeatureSetFromUrl",postCreate:function(){this.inherited(arguments);c.addClass(this.domNode,"jimu-gp-editor-sffu");c.addClass(this.domNode,
"jimu-gp-editor-base")},getValue:function(){return this.value},getGPValue:function(){var a=new D;a.where="1\x3d1";a.returnGeometry=!0;a.outFields=f.map(this.querySetting.fields,function(a){return a.name},this);a.outSpatialReference=new A(this.querySetting.spatialReference.wkid);this.queryTask=new E(this.getValue());return this.queryTask.execute(a)}});d.ObjectUrlEditor=e([g,q],{editorName:"ObjectUrlEditor",postCreate:function(){this.rest=!1;this.inherited(arguments);c.addClass(this.domNode,"jimu-gp-editor-ourl");
c.addClass(this.domNode,"jimu-gp-editor-base")},getValue:function(){return this.value},getGPValue:function(){var a;a=this.getValue()?{url:this.getValue()}:null;a=this.wrapGPValue(a);return this.wrapValueToDeferred(a)}});d.SimpleJsonEditor=e([g,v],{editorName:"SimpleJsonEditor",postMixInProperties:function(){this.inherited(arguments);"object"===typeof this.value&&(this.value=p.stringify(this.value))},postCreate:function(){this.inherited(arguments);c.addClass(this.domNode,"jimu-gp-editor-json");c.addClass(this.domNode,
"jimu-gp-editor-base")},getValue:function(){return this.value},getGPValue:function(){var a;a=this.getValue()?p.parse(this.getValue()):null;a=this.wrapGPValue(a);return this.wrapValueToDeferred(a)}});d.LayerFieldChooser=e([g,m],{editorName:"LayerFieldChooser",postCreate:function(){this.options=[];this.inherited(arguments);this.setValue(this.value);c.addClass(this.domNode,"jimu-gp-editor-lfc");c.addClass(this.domNode,"jimu-gp-editor-base")},update:function(a){this.inherited(arguments);var b=[],c;this.set("options",
[]);this.set("value","");f.some(this.map.graphicsLayerIds,function(b){if(b===a)return c=this.map.getLayer(a),!0},this);c&&this._requestLayerInfo(c.url).then(k.hitch(this,function(a){a&&a.fields&&(a=f.filter(a.fields,function(a){return"esriFieldTypeOID"!==a.type&&"esriFieldTypeGeometry"!==a.type}),b=f.map(a,function(a){return{label:a.alias||a.name,value:a.name}},this),this.set("options",b))}))},_requestLayerInfo:function(a){return F({url:a,content:{f:"json"},handleAs:"json",callbackParamName:"callback"})}});
return d});