//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/html dojo/on dojo/dom-construct dojo/query dijit/_WidgetBase dijit/_TemplatedMixin jimu/dijit/ViewStack jimu/utils".split(" "),function(p,k,q,g,m,e,l,r,s,t,n){return p([r,s],{baseClass:"jimu-header-more-popup",templateString:'\x3cdiv\x3e\x3cdiv class\x3d"pages" data-dojo-attach-point\x3d"pagesNode"\x3e\x3c/div\x3e\x3cdiv class\x3d"points jimu-corner-bottom"\x3e\x3cdiv class\x3d"points-inner"data-dojo-attach-point\x3d"pointsNode"\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e',
margin:4,postCreate:function(){this.nodes=[];this.pages=[];this.createCloseBtn()},startup:function(){this.viewStack=new t({views:[],viewType:"dom"},this.pagesNode);this.viewStack.startup();this.resize()},resize:function(){var a=this._calculateGridParam(),d;if(null!==a){g.setStyle(this.domNode,n.getPositionStyle(a.position));this.nodeWidth=a.cellSize-this.margin;if(!this.oldGridParam||this.oldGridParam.rows!==a.rows||this.oldGridParam.cols!==a.cols)this.clearPages(),this.createPages(a);this.nodes.forEach(k.hitch(this,
function(b,c){this.setItemNodePosition(b,c,a)}));this.oldGridParam=a;d=l("div.close",this.domNode)[0];g.setStyle(d,{width:0.25*this.nodeWidth+"px",height:0.25*this.nodeWidth+"px"})}else this.oldGridParam=null,g.setStyle(this.domNode,n.getPositionStyle({left:0,top:0,width:0,height:0,zIndex:111})),this.nodeWidth=0},setItemNodePosition:function(a,d,b){var c,f,h=48,e=16;c=0===d%b.cols?0:this.margin/2;f=d%(b.rows*b.cols)<b.cols?0:this.margin/2;d={};"number"===typeof this.nodeWidth&&(d.width=this.nodeWidth+
"px",d.height=this.nodeWidth+"px");"number"===typeof c&&(window.isRTL?d.marginRight=c+"px":d.marginLeft=c+"px");"number"===typeof f&&(d.marginTop=f+"px");if(c=l("img",a)[0])b.iconScaled&&(h*=this.nodeWidth/120),g.setStyle(c,{width:h+"px",height:h+"px"});if(h=l("div.node-label",a)[0])b.showLabel?(b.iconScaled&&(e*=this.nodeWidth/120),g.setStyle(h,{"font-size":e+"px",display:"block"})):g.setStyle(h,{"font-size":e+"px",display:"none"});g.setStyle(a,d)},clearPages:function(){q.forEach(this.pages,function(a){this.viewStack.removeView(a.pageNode)},
this);e.empty(this.pointsNode);this.pages=[];this.nodes=[]},createPages:function(a){var d,b,c,f;d=Math.ceil(this.items.length/(a.rows*a.cols));for(b=0;b<d;b++)c=e.create("div",{"class":"page"}),this.createPageItems(b,c,a),this.viewStack.addView(c),1<d&&(f=e.create("div",{"class":"point"},this.pointsNode),this.own(m(f,"click",k.hitch(this,this._onPageNodeClick,b)))),this.pages.push({pageNode:c,pointNode:f});0<this.viewStack.views.length&&this._selectPage(0)},_onPageNodeClick:function(a){this._selectPage(a)},
_selectPage:function(a){1<this.pages.length&&(l(".point",this.domNode).removeClass("point-selected"),g.addClass(this.pages[a].pointNode,"point-selected"));this.viewStack.switchView(this.pages[a].pageNode)},createPageItems:function(a,d,b){var c,f;c=this.items.length;f=b.rows*b.cols;b=a*f;a=(a+1)*f;f=a-c;for(a=Math.min(a,c);b<a;b++)this.createItemNode(b,d);for(b=c;b<c+f;b++)this.createEmptyItemNode(d)},createItemNode:function(a,d){var b,c;c=this.items[a];b=e.create("div",{"class":"icon-node jimu-float-leading",
title:c.label,settingId:c.id},d);e.create("img",{src:c.icon},b);e.create("div",{"class":"node-label",title:c.label,innerHTML:c.label},b);b.config=c;this.own(m(b,"click",k.hitch(this,function(){this.onNodeClicked(b)})));this.nodes.push(b)},createEmptyItemNode:function(a){a=e.create("div",{"class":"icon-node jimu-float-leading"},a);this.nodes.push(a);return a},createCloseBtn:function(){var a;a=e.create("div",{"class":"close"},this.domNode);e.create("div",{"class":"close-inner"},a);m(a,"click",k.hitch(this,
function(){this.hide()}));return a},hide:function(){g.setStyle(this.domNode,"display","none")},show:function(){g.setStyle(this.domNode,"display","block")},onNodeClicked:function(a){this.hide()},_calculateGridParam:function(){var a,d,b,c,f=!1,e=!0;a=g.getContentBox(jimuConfig.mapId);d=Math.min(a.w,a.h)-40;if(360<=d)c=120;else{c=Math.floor(d/3);if(10>c)return null;f=!0;80>c&&(e=!1)}d=Math.floor((a.h-40)/c);b=Math.floor((a.w-40)/c);d=4<d?4:d;d=3>d?3:d;b=3>d?3:4<b?4:b;return{rows:d,cols:b,cellSize:c,
iconScaled:f,showLabel:e,position:{top:(a.h-c*d)/2,bottom:(a.h-c*d)/2,left:(a.w-c*b)/2,right:(a.w-c*b)/2,width:c*b-this.margin*(b-1)/2,height:c*d-this.margin*(d-1)/2,zIndex:111}}}})});